-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versi server:                 5.7.33 - MySQL Community Server (GPL)
-- OS Server:                    Win64
-- HeidiSQL Versi:               11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- membuang struktur untuk table amora.akun
CREATE TABLE IF NOT EXISTS `akun` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_level` int(11) DEFAULT NULL,
  `nama` varchar(100) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.akun: ~1 rows (lebih kurang)
/*!40000 ALTER TABLE `akun` DISABLE KEYS */;
INSERT INTO `akun` (`id`, `id_level`, `nama`, `username`, `password`) VALUES
	(1, 13, 'Oka Wiadnyana', 'oka', '$2y$10$7TFWUvTgVxru8PpnFvlaeOSSJybjUzIazTRguUUT031PHFV/kJFQa'),
	(2, 11, 'Vio', 'vio', '$2y$10$vcjksMQArcU1es7sfOZwl.tK03XlPBUTMVC8EUacVMjC6XEJGbVXS');
/*!40000 ALTER TABLE `akun` ENABLE KEYS */;

-- membuang struktur untuk table amora.apm
CREATE TABLE IF NOT EXISTS `apm` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nomor` int(10) unsigned DEFAULT NULL,
  `area` varchar(50) DEFAULT NULL,
  `penilaian` text,
  `uraian` text,
  `area_zi` text,
  `bobot` text,
  `jumlah_sub` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=196 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.apm: ~195 rows (lebih kurang)
/*!40000 ALTER TABLE `apm` DISABLE KEYS */;
INSERT INTO `apm` (`id`, `nomor`, `area`, `penilaian`, `uraian`, `area_zi`, `bobot`, `jumlah_sub`) VALUES
	(1, 1, 'KETUA', 'Manual Mutu :                                                           - Struktur TIM PMPN                                                              - TUSI                                                                                                          - Sasaran Mutu                                                                           - Kebijakan Mutu                                                                                               - Peta Proses Bisnis APM         ', '1. Selalu diperbarui\n2. Sudah disosialisasikan (dibuktikan dengan data dukung berupa \n    notulen)\n3. Manual Mutu sudah diterapkan dengan baik\n    (dibuktikan dengan pelaksanaan asesmen internal 2 kali   \n   setahun, RTM, evaluasi sasaran mutu dll)\n4. Manual mutu dievaluasi minimal setahun sekali dan \n   ditindaklanjuti (dibuktikan dengan data dukung)', 'Area 6\n', 'Berat', 4),
	(2, 2, 'KETUA', 'Pelaksanaan Pengawasan dan Pembinaan sesuai dengan PERMA No. 7 Tahun 2016', '1. Sudah disosialisasikan minimal setahun sekali (dibuktikan \n    dengan data dukung berupa notulen)\n2. Absensi sudah diterapkan sesuai dengan\n    format Perma No. 7 tahun 2016 baik\n    secara manual maupun Finger print atau \n    elektronik (menyesuaikan dengan sikon)\n3. Surat izin keluar kantor, surat cuti, izin\n    keluar negeri, surat tugas, surat cuti\n    sakit sudah diterapkan sesuai dengan\n    format Perma No. 7 tahun 2016\n4. Sudah dimonitoring & dievaluasi dan\n    ditindaklanjuti', 'Area 5', 'Sedang', 4),
	(3, 3, 'KETUA', 'Pelaksanaan Pengawasan Melekat dan Pembinaan sesuai dengan PERMA No. 8 Tahun 2016', '1. Sudah disosialisasikan minimal setahun sekali (dibuktikan \n    dengan data dukung berupa notulen)\n2. Masing-masing pejabat sudah  \n    melakukan pembinaan dan pengawasan melekat\n3. Sudah dimonitoring dan dievaluasi \n4. Sudah ditindaklanjuti dalam bentuk\n    pemberian sanksi atau penghargaan', 'Area 5', 'Sedang', 4),
	(4, 4, 'KETUA', 'Pelaksanaan Pengawasan dan Pembinaan sesuai dengan PERMA No. 9 Tahun 2016', '1. Sudah disosialisasikan minimal setahun sekali (dibuktikan \n    dengan data dukung berupa notulen)\n2. Sudah melengkapi sarana pengaduan, antara \n    lain:\n    a. aplikasi SIWAS MA-RI pada situs\n        Mahkamah Agung;\n    b. layanan pesan singkat/SMS;\n    c. surat elektronik (e-mail);\n    d. faksimile;\n    e. telepon;\n    f.  meja Pengaduan;\n    g. form Pengaduan; dan/atau\n    h. kotak Pengaduan.\n3. Sudah dimonitoring dan dievaluasi 1 bulan sekali\n4. Sudah ditindaklanjuti sesuai ketentuan \n    Pasal 6 dan Pasal 7 Perma Nomor 9 \n    Tahun 2016', 'Area 5\n', 'Sedang', 4),
	(5, 5, 'KETUA', 'Telah dilaksanakan pembagian tugas antara KPN dengan WKPN serta telah bekerja sama dengan baik', 'Sudah ada SK pembagian tugas, sudah dilaksanakan dan koordinasi berjalan dengan baik sesuai SEMA Nomor 2 Tahun 1988 ', 'Area 2,4', 'Berat', 1),
	(6, 6, 'KETUA', 'Pelaksanaan Rapat Evaluasi Kinerja \n', '1. Rapat rutin secara berkala dimulai\n    secara berjenjang dari satuan terkecil\n    (Kasubbag / Panmud) didampingi Hakim\n    Pengawas Bidang dan dibuktikan\n    dengan notulen rapat\n2. Melakukan evaluasi kinerja minimal 3 bulan sekali\n3. Tindak lanjut hasil evaluasi\n4. Terdokumentasi dengan baik', 'Area 4', 'Berat', 4),
	(7, 7, 'KETUA', '1. Dokumen SAKIP \na.  Indikator Kinerja Utama (IKU) \nb.  Rencana Strategis (RENSTRA) \nc.  Recana Kinerja Tahunan (RKT) \nd.  RENJA - RKAK/L \ne.  Perjanjian Kinerja Tahunan (PKT) \nf.  Laporan Kinerja Instansi Pemerintah\n    (LKjIP) (Pengukuran Kinerja = Realisasi :\n    Target X 100%) \n2. Laporan Tahunan PN yang bersangkutan', '1. Dokumen Lengkap dan sesuai                                                                                                                                     \n2. Penyusunannya melibatkan seluruh\n    unsur pimpinan dan pegawai\n3. Nilai LKJIP minimal "BB"', 'Area 4', 'Berat', 3),
	(8, 8, 'KETUA', 'Indikator Kinerja Utama (IKU) ', '   IKU telah menggambarkan fungsi utama\n    (core business)  dan telah di reviu\n    Dibuktikan dengan data dukung berupa :\n    a. Dokumen IKU\n    b. Dokumen rapat (undangan, daftar hadir)', 'Area 4', 'Sedang', 1),
	(9, 9, 'KETUA', 'Dokumen Rencana Strategis (RENSTRA)', '1. RENSTRA telah menyajikan Indikator\n     Kinerja Utama (IKU), tujuan dan\n     sasaran organisasi \n2. RENSTRA telah berorientasi pada hasil.\n    (dibuktikan dengan data dukung)', 'Area 4', 'Sedang', 2),
	(10, 10, 'KETUA', 'Dokumen Rencana Kinerja Tahunan (RKT)', '1. RKT telah sesuai dengan Indikator Kinerja Utama (IKU)\n2. RKT telah digunakan sebagai acuan dalam penyusunan \n   anggaran / RKA dan Perjanjian Kinerja.\n   (dibuktikan dengan data dukung)', 'Area 4', 'Berat', 1),
	(11, 11, 'KETUA', 'Dokumen Laporan Kinerja Instansi Pemerintah (LKjIP)', '1. Penyusunan LKjIP  melibatkan seluruh\n    unsur pimpinan \n2. LKjIP telah menyajikan evaluasi dan\n    analisis atas capaian kinerja\n3. LKjIP  telah disampaikan tepat  waktu\n4. LKjIP telah disosialisasikan \n   ', 'Area 4', 'Berat', 4),
	(12, 12, 'KETUA', 'Hasil Monitoring dan Evaluasi LKjIP ', '1. Evaluasi LKJIP melibatkan seluruh\n     unsur pimpinan (data dukung)\n2. Evaluasi LKJIP dilaksanakan pada tahun\n    nilai dikeluarkan\n3. Hasil evaluasi ditindaklanjuti dan dikirimkan\n    ke PT serta disosialisasikan ke seluruh\n    jajaran\n4. Hasil evaluasi dan tindaklanjut\n    terdokumentasi dengan baik ', 'Area 4,5', 'Sedang', 4),
	(13, 13, 'KETUA', 'Penetapan Majelis Hakim dan PP', '1. Penetapan majelis sudah sepenuhnya menggunakan SIPP\n2. Penetapan PP sudah sepenuhnya menggunakan SIPP \n3. Penginputan Penetapan dalam SIPP diinput  1 X 24 jam\n4. Diinput oleh masing-masing pemilik user (Ketua dan Panitera)', 'Area 2', 'Sedang', 4),
	(14, 14, 'KETUA', 'Pengawasan Eksekusi ', '1.Seluruh permohonan eksekusi sudah terdata pada \n    SIPP \n2. KPN melakukan monev terhadap pelaksanaan \n    permohonan eksekusi secara manual dan melalui aplikasi \n    PERKUSI setiap bulan dan terdokumentasi dengan baik       \n3. KPN menyurati Pemohon untuk menanyakan \n    kelanjutan proses, jika dalam waktu 30 hari setelah \n    aanmaning tidak ada tindaklanjut dari Pemohon \n    Eksekusi, selanjutnya jika berdasarkan jawaban \n    Pemohon sudah ditindak lanjuti secara sukarela \n    maka diproses sesuai buku pedoman eksekusi \n    Ditjen badilum dan didata ke dalam SIPP, apabila \n    dalam waktu 30 hari pihak tidak menjawab maka atas \n    perintah  KPN, dilakukan penutupan jurnal keuangan eksekusi \n    dan dicatatkan dalam SIPP                           \n4. Seluruh data disetiap tahapan eksekusi yang harus diisi pada \n    SIPP telah terisi 100 % ', 'Area 2,6\n', 'Sedang', 4),
	(15, 15, 'KETUA', 'Pelaporan Pelaksanaan Eksekusi kepada KPT dalam rangka melaksanakan Surat  WKMA Bidang Yudisial Nomor 59/WK.MA.Y/X/2019 tanggal 30 Oktober 2019 Perihal Eksekusi ', '1. Sudah melaksanakan monitoring dan evaluasi terhadap penyelesaian permohonan eksekusi terutama menyangkut permohonan eksekusi yang belum dilaksanakan (data dukung)\n2. KPN meminta arahan KPT untuk Eksekusi yang \n   tidak dapat dilaksanakan    sesuai Surat  WKMA Bidang Yudisial Nomor 59/WK.MA.Y/X/2019 tanggal 30 Oktober 2019\n3. Sudah melaporkan seluruh permohonan eksekusi (baik yang sudah maupun yang belum dilaksanakan) kepada KPT setiap 6 bulan. \n4. Sudah terdokumentasi dengan baik', 'Area 2, 5\n', 'Berat', 4),
	(16, 16, 'KETUA', 'Penerapan Restorative Justice ', '1. Sudah disosialisasikan secara berkala \n2. Melakukan diskusi reguler tentang penerapan RJ di pengadilan yang diikuti oleh seluruh hakim (data dukung)\n3. Sudah melakukan monev secara berkala tentang penerapan RJ \n4.Melaporkan hasil evaluasi penerapan RJ kepada KPT setiap sebulan sekali\n', 'Area 1', 'Sedang', 4),
	(17, 17, 'KETUA', 'Gugatan Sederhana (GS) berdasarkan \nPERMA Nomor 4 Tahun 2019', '1. Sudah disosialisasikan ke pihak eksternal melalui berbagai media \n2. Petugas Meja Perdata memahami syarat pendaftaran Gugatan \n    Sederhana\n3. Sudah melakukan monev secara berkala tentang penerapan GS \n4 .Melaporkan hasil evaluasi penerapan GS kepada KPT setiap \n    sebulan sekali', 'Area 2,5,6', 'Sedang', 4),
	(18, 18, 'KETUA', 'Monitoring Administrasi Biaya Perkara', 'KPN sesuai buku II memerintahkan Panitera secara mendadak untuk  meneliti kebenaran setiap penerimaan dan pengeluaran uang perkara kesesuaian antara pencatatan dibuku jurnal dengan uang yang dibrankas maupun di bank setiap 3 bulan sekali (4x dalam setahun) dan dibuatkan BAP', 'Area 4,5,6', 'Berat', 1),
	(19, 19, 'KETUA', 'Kelengkapan SPPA sesuai dengan SK Dirjen Nomor 2176/DJU/SK/PS01/12/2017', 'Kelengkapan SPPA \n1. Ruang tunggu ramah anak korban/saksi,\n2. Ruang tunggu ramah anak pelaku (berteralis)\n3. Ruang sidang anak, \n4. Ruang BaPas/PekSos, \n5. Ruang Diversi/Mediasi,\n6. Ruang Kaukus, \n7. Sarana Teleconfrence.', 'Area 5,6', 'Sedang', 7),
	(20, 20, 'KETUA', 'Layanan Disabilitas di Pengadilan \nsesuai SK Dirjen No 1692/DJU/SK/PS.00/12/2020', '1. Sudah mensosialisasikan kepada seluruh jajaran pengadilan                                            \n2. Sudah menerapkan Form penilaian personal\n3. Sudah memastikan sarana dan prasarana layanan disabilitas tersedia seluruhnya\n4. Mengadakan MoU dengan Dinas Sosial, Dinas Pendidikan, SLB, organisasi penyandang disabilitas dll\n5. Sudah menerapkan Antrian prioritas pada setiap layanan pengadilan\n6. Sudah membuat SOP untuk layanan pengadilan bagi penyandang disabilitas\n7. sudah melakukan Bimtek Internal untuk layanan disabilitas\n', 'Area 2,6\n', 'Sedang', 7),
	(21, 21, 'KETUA', 'Tata tertib persidangan', '1. Ada SK KPN tentang penunjukkan petugas piket sidang\n2. Petugas piket sidang memahami tugasnya sesuai yang \n    tertuang pada SK KPN\n3. Tata tertib persidangan sudah terinformasikan\n    untuk pengunjung di setiap ruang sidang \n4. Hakim dan Panitera sudah masuk dan keluar\n    dari ruang sidang melalui pintu tersendiri\n5. Sudah dilakukan Monitoring dan evaluasi\n    terhadap tata tertib dan pengamanan\n    persidangan pada setiap rapat bulanan (data\n    dukung notulen rapat dan dokumen lainnya)', 'Area 6', 'Sedang', 5),
	(22, 22, 'KETUA', 'Persidangan Elektronik', '1. Satker sudah mengadakan bimtek/sosialisasi E-litigasi secara berkala baik ke pihak Eksternal maupun Internal Pengadilan\n2. E-litigasi sudah dilaksanakan minimal 50% dari perkara yang sudah didaftarkan secara ecourt\n3.Monev pelaksanaan persidangan elektronik dengan melakukan diskusi reguler (data dukung)\n4.Pimpinan selalu memberikan arahan (minimal satu tahun sekali) dan memastikan pelaksanaan persidangan secara elektronik berjalan baik dan sesuai ketentuan (notulen)\n', 'Area 2,6\n', 'Sedang', 4),
	(23, 23, 'KETUA', 'Pelaksanaan Pembangunan Zona Integritas', '1. Internalisasi pembangunan Zona Integritas \n2. Public Campaign pembangunan Zona Integritas\n3. Keterlibatan Pimpinan pada setiap kegiatan pembangunan \n    Zona Integritas\n4. Program perubahan yang diusung Pengadilan \n5. TLHP Internal dan Eksternal 100 %\n6. Nilai IPAK minimal 3,60 \n7. Nilai IKM minimal 3,60 \n8. Terdokumentasi dengan baik', 'Area 1', 'Berat', 8),
	(24, 24, 'KETUA', 'Pengimplementasian core values ASN  BerAKHLAK (Surat Edaran Menpan RB Nomor 20 Tahun 2021)\na.Berorientasi Pelayanan\nb. Akuntabel\nc. Kompeten\nd.Harmonis\ne. Loyal\nf. Adaptif\ng. Kolaboratif\n', '1. Sudah disosialisasikan (data dukung)\n2. Setiap unit kerja sudah mengenal core values ASN BerAKHLAK\n    (uji petik)\n3. Sudah melakukan inovasi untuk membudayakan BerAKHLAK\n4. Sudah di Monev (data dukung)\n', 'Area 1', 'Berat', 4),
	(25, 25, 'KOORDINATOR AREA', 'AREA 1 ZI Manajemen Perubahan \n(Pemenuhan )', '1. Ada Dokumen rencana aksi/kegiatan dan sudah \n    dimonev\n2. Tim kerja yang dilengkapi dengan Daftar Riwayat \n    Hidup dan Notulen Rapat Pembentukan\n3. Pemantauan/Monitoring dan evaluasi\n    pembangunan WBK/WBBM di setiap area per bulan\n4. Program kerja untuk Perubahan pola\n    pikir dan budaya kerja\n5. SK Penetapan Role Model KPN\n6. SK Penetapan Agen Perubahan', 'Area 1', 'Sedang', 6),
	(26, 26, 'KETUA', 'Penetapan Agen Perubahan (Permenpan Nomor 52 Tahun 2014 dan Permenpan Nomor 27 Tahun 2014)', '1. Agen Perubahan diusulkan oleh masing-masing pimpinan unit kerja kepada Tim ZI (Area 1) dengan mempertimbangkan kriteria :\n- Berstatus ASN\n- Tidak sedang menjalani Hukuman Disiplin\n- Bertanggung jawab sesuai dengan bidangnya\n- Taat  dan Konsisten terhadap aturan disiplin dan Kode Etik \n   pegawai\n- Mampu memberikan pengaruh positif, inovatif dan proaktif.\n  (dibuktikan dengan pengusulan dari masing-masing unit kerja)\n2. SK Penetapan Agen Perubahan (Perorangan/Tim) yang ditetapkan oleh KPN berdasarkan rekomendasi Area I\n3. Program Perubahan yang diusung harus memenuhi minimal \n   salah satu kriteria :\n- Mendorong peningkatan capaian kinerja utama.\n- Mendorong penguatan integritas serta mengatasi isu strategis, \n- Mendorong peningkatan kualitas layanan bagi pengguna layanan                                             \n4. Rencana tindak Agen Perubahan sesuai dengan lampiran Permenpan Nomor 27 Tahun 2014, Bab III, Tabel I halaman 10 \n5. Monev Tindak Agen Perubahan sesuai dengan lampiran Permenpan Nomor 27 Tahun 2014, Bab III, Tabel II halaman 13 dilakukan oleh Area I dan dilaporkan kepada Pimpinan\n6. Pemilihan dilaksanakan setiap tahun', 'Area 1', 'Sedang', 4),
	(27, 27, 'KETUA', 'Penetapan Role Model (Permenpan Nomor 52 Tahun 2014)\nPimpinan berperan sebagai role model dalam pembangunan Zona Integritas', '1. KPN ditetapkan dengan SK KPT sebagai Role Model di \n    Pengadilan Negeri\n2. Selalu diperbarui setiap penggantian pimpinan \n3. KPN sebagai role model sudah mendorong kedisiplinan, prestasi \n    kerja, peningkatan kinerja, pengembangan pola pikir dan budaya \n    kerja di satkernya dengan  program yang terukur\n4.Terdokumentasi dengan baik', 'Area 1', 'Sedang', 4),
	(28, 28, 'KETUA', 'Penandatanganan Pakta Integritas', '1. Sudah dilaksanakan sesuai PERMENPAN No.\n     52 Tahun 2014 dan Surat Sekma NO.\n     131/1/SEK/KU.01/6/2016\n2. Sudah diperbarui setiap tahun\n3. Pelaksanaannya dilakukan secara resmi\n4. Terdokumentasi dengan baik', 'Area 1', 'Ringan', 4),
	(29, 29, 'KOORDINATOR AREA', 'AREA 1 ZI Manajemen Perubahan \n( Reform )', '1. Agen perubahan telah membuat perubahan yang konkret di Instansi dalam 1 tahun\n(Setiap agen perubahan mempunyai program perubahan)\n2. Perubahan yang dibuat Agen Perubahan telah terintegrasi dalam sistem manajemen ( Seluruh perubahan telah diintegrasikan dalam sistem manajemen )\n3. Pimpinan memiliki komitmen terhadap pelaksanaan reformasi birokrasi, dengan adanya target capaian reformasi yang jelas di dokumen perencanaan\n4. Instansi membangun budaya kerja positif dan menerapkan nilai-nilai organisasi dalam pelaksanaan tugas sehari-hari\n', 'Area 1', 'Berat', 4),
	(30, 30, 'KOORDINATOR AREA', 'AREA 2 ZI Penataan Tatalaksana ( Pemenuhan )', '1. SOP mengacu pada peta proses bisnis instansi\n2. Prosedur operasional tetap (SOP) telah diterapkan\n3. Prosedur operasional tetap (SOP) telah dievaluasi\n4. Sistem pengukuran kinerja unit sudah menggunakan teknologi informasi\n5. Operasionalisasi manajemen SDM sudah menggunakan teknologi informasi\n6. Pemberian pelayanan kepada publik sudah menggunakan teknologi informasi\n7. Telah dilakukan monitoring dan dan evaluasi terhadap pemanfaatan teknologi informasi dalam pengukuran kinerja unit, operasionalisasi SDM, dan pemberian layanan kepada publik\n8. Kebijakan tentang  keterbukaan informasi publik telah diterapkan\n9. Telah dilakukan monitoring dan evaluasi pelaksanaan kebijakan keterbukaan informasi publik', 'Area 2', 'Sedang', 9),
	(31, 31, 'KOORDINATOR AREA', 'AREA 2 ZI Penataan Tatalaksana ( Reform )', '`1. Telah disusun peta proses bisnis dengan adanya penyederhanaan jabatan\n2. Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan publik yang lebih cepat dan efisien\n3. Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan internal organisasi yang lebih cepat dan efisien\n4. Transformasi digital pada bidang proses bisnis utama telah mampu memberikan nilai manfaat bagi unit kerja secara optimal \n5. Transformasi digital pada bidang administrasi pemerintahan telah mampu memberikan nilai manfaat bagi unit kerja secara optimal\n6. Transformasi digital pada bidang pelayanan publik telah mampu memberikan nilai manfaat bagi unit kerja secara optimal', 'Area 2', 'Sedang', 6),
	(32, 32, 'KOORDINATOR AREA', 'AREA 3 ZI Penataan SDM ( Pemenuhan )', '1. Kebutuhan pegawai mengacu kepada peta jabatan dan hasil analisa beban kerja \n2. Penempatan pegawai hasil rekrutmen murni mengacu kepada kebutuhan pegawai \n3. Penempatan pegawai hasil rekrutmen dan mutasi pegawai telah memberikan perbaikan terhadap kinerja unit kerja (data dukung hasil monev)\n4. Telah dilakukan mutasi pegawai antar jabatan dengan memperhatikan kompetensi jabatan dan mengikuti pola mutasi internal\n5. Telah dilakukan Training Need Analysis dan mempertimbangkan hasil pengelolaan kinerja pegawai untuk pengembangan kompetensi \n6. Pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat atau telah diikutsertakan pada lembaga pelatihan, in-house training, coaching, mentoring dan sejenisnya untuk pengembangan kompetensi\n7. Telah dilakukan monitoring dan evaluasi terhadap hasil pengembangan kompetensi dalam kaitannya dengan perbaikan kinerja\n8. Terdapat penetapan kinerja individu yang terkait dengan perjanjian kinerja organisasi\n9. Ukuran kinerja individu telah memiliki kesesuaian dengan indikator kinerja individu level diatasnya\n10. Pengukuran kinerja individu dilakukan secara periodik\n11. Hasil penilaian kinerja individu telah dijadikan dasar untuk pemberian reward\n12. Aturan disiplin/kode etik/kode perilaku telah dilaksanakan/diimplementasikan\n13. Data informasi kepegawaian unit kerja telah dimutakhirkan secara berkala', 'Area 3', 'Sedang', 10),
	(33, 33, 'KOORDINATOR AREA', 'AREA 3 ZI Penataan SDM ( Reform )', '1. Ukuran kinerja individu telah berorientasi hasil (outcome) \n2. Hasil assemen telah dijadikan pertimbangan untuk mutasi dan pengembangan karir pegawai\n3. Penurunan pelanggaran disiplin pegawai\n(Data dukung berupa monev terhadap:\n- Jumlah pelanggaran tahun sebelumnya\n- Jumlah pelanggaran tahun ini\n- Jumlah pelanggaran yang telah diberikan sanksi/hukuman)\n4.Terdokumentasi dengan baik', 'Area 3', 'Sedang', 4),
	(34, 34, 'KETUA', 'AREA 4 ZI Penguatan Akuntabilitas \n(Pemenuhan )', '1. Pimpinan terlibat secara langsung pada saat penyusunan perencanaan dan penyusunan penetapan kinerja\n2. Pimpinan memantau pencapaian kinerja secara berkala\n3. Terdapat sistem informasi/mekanisme informasi kinerja\n4. Unit kerja telah berupaya meningkatkan kapasitas SDM yang menangangi akuntabilitas kinerja', 'Area 4', 'Berat', 4),
	(35, 35, 'KOORDINATOR AREA', 'AREA 4 ZI Penguatan Akuntabilitas\n (Reform )', '1. Persentase capaian pada sasaran kinerja 100% atau lebih\n     (Data dukung berupa monev terhadap Jumlah Sasaran Kinerja dan Jumlah \n      Sasaran Kinerja yang tercapai 100% atau lebih)\n2. Hasil Capaian/Monitoring Perjanjian Kinerja telah dijadikan dasar sebagai \n    pemberian reward and punishment bagi organisasi\n3.Terdapat penjenjangan kinerja yang mengacu pada kinerja utama organisasi\n4.Terdokumentasi dengan baik', 'Area 4', 'Sedang', 4),
	(36, 36, 'KOORDINATOR AREA', 'AREA 5 Penguatan Pengawasan (Pemenuhan)', '1.Pengendalian gratifikasi telah dipublikasikan/dikampaanyekan dan telah diimplementasikan\n2.Telah dibangun lingkungan pengendalian\n3.Telah dilakukan penilaian risiko dan kegiatan pengendalian untuk meminimalisir risiko yang telah diidentifikasi dalam suatu manajemen risiko\n4.SPI telah diinformasikan dan dikomunikasikan kepada seluruh pihak terkait\n5.Pengaduan masyarakat telah dikelola dengan baik (diimplementasikan, dimonev dan ditindaklanjuti)\n', 'Area 5', 'Sedang', 5),
	(37, 37, 'KOORDINATOR AREA', 'Sistem Pengendalian Intern Pemerintah/ SPIP (Manajemen Risiko)', '1. Telah ditetapkan Tim Manajemen Risiko \n2. Manajemen Risiko disusun sesuai dengan \n   Keputusan Sekma Nomor  475/SEK/SK/VII/2019                         3.Telah menentukan isu internal dan eksternal\n4.Telah dibuat langkah-langkah antisipasi\n   penanganan risiko (identifikasi risiko)\n5. Melakukan analisa dan Pimpinan menentukan \n    level risiko\n6. Sudah dimonitoring, evaluasi dan   \n    ditindaklanjuti. (minimal satu tahun sekali \n    atau setiap ada perubahan)', 'Area 5', 'Berat', 6),
	(38, 38, 'KOORDINATOR AREA', 'Sistem Pengendalian Intern Pemerintah/ SPIP (Pemantauan Pengendalian Intern/ Monitoring Evaluasi)', '1. Tim SPIP/Manejemen risiko mendeteksi\n    setiap perubahan intern dan ekstern dalam\n    kegiatan monitoring setiap bulan (data dukung)\n2.Tim SPIP/ Manejemen risiko  memastikan\n    efektivitas pengendalian risiko melalui kegiatan\n    monitoring dan evaluasi setiap tahun sekali\n    (data dukung)\n3. Melakukan kegiatan identifikasi risiko baru,\n    melalui kegiatan monitoring dan evaluasi setiap\n    tahun sekali (data dukung)\n4. Melakukan sosialiasi perubahan SPIP\n    setiap tahunnya', 'Area 5', 'Sedang', 4),
	(39, 39, 'KOORDINATOR AREA', 'Penanganan Benturan Kepentingan (SK Sekma 59A/Sek/SK/11/2014)', '1. Sudah ada SK Tim dan SK tatacara\n     Penanganan Benturan Kepentingan, \n2. Sudah disosialisasikan/Internalisasi oleh KPN tentang\n     Penanganan Benturan Kepentingan\n3. Sudah dimonitoring, dievaluasi \n4. Sudah ditindaklanjuti\n', 'Area 5', 'Ringan', 4),
	(40, 40, 'KOORDINATOR AREA', 'Pengendalian gratifikasi sesuai dengan Pedoman Pengendalian Gratifikasi dari KPK', '1. Sudah ada SK Tim Pengendali Gratifikasi\n2. Sudah ada SK tatacara penanganan gratifikasi \n3. Sudah disosialisasikan oleh KPN tentang\n    pengendalian gratifikasi\n4. Sudah dimonitoring, dievaluasi dan\n    ditindaklanjuti', 'Area 5', 'Ringan', 4),
	(41, 41, 'KOORDINATOR AREA', 'AREA 5 Penguatan Pengawasan (Reform)', '1.Telah dilakukan mekanisme pengendalian aktivitas secara berjenjang\n2. Persentase penanganan pengaduan masyarakat\n(Jumlah pengaduan masyarakat yang harus ditindaklanjuti, jumlah pengaduan masyarakat yang sedang diproses, jumlah pengaduan masyarakat yang  selesai ditindaklanjuti)\n3.Persentase penyampaian LHKPN 100%\n4.Persentase penyampaian LHKASN 100%\n', 'Area 5', 'Sedang', 4),
	(42, 42, 'KETUA', 'Pelaporan E-LHKPN', '1. Sudah dilaksanakan dengan benar\n2. Sudah dilaksanakan tepat waktu setiap tahun/\n    setiap ada promosi dan mutasi\n3. Seluruh tenaga teknis dan pejabat struktural\n    sudah melaporkan (100%) per maret setiap\n    tahunnya\n4. Tanda terima dari KPK sudah di upload\n    seluruhnya ke aplikasi SIKEP', 'Area 5', 'Berat', 4),
	(43, 43, 'KETUA', 'Pelaporan E-LHKASN', '1. Sudah dilaksanakan tepat waktu :\n     - 1 (satu) bulan setelah pejabat sebagaimana\n       dimaksud tersebut diangkat dalam jabatan,\n       mutasi atau promosi atau;\n     - 1 (satu) bulan setelah berhenti dari jabatan\n       oleh seluruh ASN yang wajib lapor (100%)\n2. Bukti pelaporan dari SIHARKA sudah diunggah   \n    seluruhnya ke aplikasi SIKEP\n3. Bukti pelaporan dari SIHARKA sudah\n    terpublikasikan seluruhnya pada website\n    pengadilan\n4. Terdokumentasi dengan baik', 'Area 5', 'Berat', 4),
	(44, 44, 'KETUA', 'AREA 6 Peningkatan Kualitas Pelayanan (Pemenuhan)', '1.Terdapat kebijakan standar pelayanan\n2.Terdapat media pengaduan dan konsultasi pelayanan yang terintegrasi dengan SP4N-Lapor!\n3.Terdapat unit yang mengelola pengaduan dan konsultasi pelayanan\n4.Telah dilakukan evaluasi atas penanganan keluhan/masukan dan konsultasi\n5.Telah membangun database pelayanan yang terintegrasi\n6.Penerapan Pelayanan Prima\n', 'Area 6', 'Berat', 6),
	(45, 45, 'KOORDINATOR AREA', 'Pelayanan Prima', '1.Telah dilakukan berbagai upaya peningkatan kemampuan dan/atau kompetensi tentang penerapan budaya pelayanan prima\n2.Informasi tentang pelayanan mudah diakses melalui berbagai media\n3.Telah terdapat sistem pemberian penghargaan dan sanksi bagi petugas pemberi pelayanan\n4.Telah terdapat sistem pemberian kompensasi kepada penerima layanan bila layanan tidak sesuai standar\n5.Terdapat sarana layanan terpadu/terintegrasi (PTSP)\n6.Terdapat inovasi pelayanan\n7.Telah dilakukan perbaikan secara terus menerus\n8.Telah menerapkan teknologi informasi dalam memberikan pelayanan', 'Area 6', 'Sedang', 8),
	(46, 46, 'KETUA', 'Maklumat Pelayanan sesuai Permenpan No. 15 Tahun 2014 Tentang Pedoman Standar Pelayanan.', '1. Maklumat pelayanan sudah\n   dideklarasikan sesuai dengan isi\n   PERMENPAN No.15 Tahun 2014 Tentang\n   Pedoman Standar Pelayanan \n2. Sudah disosialisasikan melalui berbagai\n    media \n3. Penempatan Maklumat Pelayanan di PTSP dan tempat lainnya yang mudah dilihat pengguna layanan\n4. Sudah dimonitoring, dievaluasi,\n    ditindaklanjuti', 'Area 6', 'Berat', 4),
	(47, 47, 'KOORDINATOR AREA', 'Standar Pelayanan Pengadilan sesuai SK. KMA No. 026/KMA/SK/II/2012 dan Permenpan Nomor 15 Tahun 2014', '1. Standar pelayanan yang memuat unsur-\n    unsur  : dasar hukum, persyaratan,\n    prosedur, jangka waktu penyelesaian  \n    layanan,biaya, produk dan pengelolaan \n    pengaduan sudah tepat dan sudah ditetapkan\n2. Standar pelayanan telah dimaklumatkan \n3. Standar pelayanan telah disosialisasikan/ dipublikasikan kepada petugas dan pengguna\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti/diperbaiki.', 'Area 6', 'Berat', 4),
	(48, 48, 'KOORDINATOR AREA', 'AREA 6 Peningkatan Kualitas Pelayanan (Reform)', '1.Inovasi yang mendorong perbaikan pelayanan publik pada:\n-Kesesuaian Persyaratan dan atau\n- Kemudahan Sistem, Mekanisme, dan Prosedur dan atau\n- Kecepatan Waktu Penyelesaian dan atau\n- Kejelasan Biaya/Tarif, Gratis dan atau\n- Kualitas Produk Spesifikasi Jenis Pelayanan dan atau\n- Kompetensi Pelaksana/Web dan atau\n- Perilaku Pelaksana/Web dan atau\n- Kualitas Sarana dan prasarana dan atau\n- Penanganan Pengaduan, Saran dan Masukan\n2.\'Inovasi pada perijinan/pelayanan telah dipermudah, Waktu lebih cepat, Pelayanan Publik yang terpadu, alur lebih pendek/singkat dan terintegrasi dengan aplikasi\n3 Jumlah Penguna layanan terdokumentasi dengan baik\n4.\'Penanganan pengaduan pelayanan dilakukan melalui berbagai kanal/media secara responsive dan bertanggung jawab', 'Area 6', 'Sedang', 4),
	(49, 49, 'KETUA', 'Monitoring  SEMA Nomor 1 tahun 2011 tentang Perubahan Surat Edaran Mahkamah Agung No 2 Tahun 2010 tentang Penyampaian Salinan dan Petikan Putusan', 'Sudah dilakukan monitoring evaluasi terhadap :\n1. Penyampaian salinan putusan pidana maksimal 14 hari setelah putusan dibacakan\n2.untuk perkara perdata, salinan sudah siap 14 hari setelah putusan dibacakan  \n3. Penyampaian putusan pidana kepada\n    terdakwa, JPU, Rutan/LP\n4. Sudah dilakukan secara berkala setiap bulan\n5. Hasil Monev sudah ditindaklanjuti\n6. Pelaksanaan sudah didokumentasikan\n    dengan baik', 'Area 2,5,6', 'Sedang', 6),
	(50, 50, 'KETUA', 'Monitoring Dan Evaluasi SPPT TI', '1. Melakukan sosialisasi SPPT TI\n2. Melakukan Monitoring \n3. Melakukan Evaluasi dan sudah ditindaklanjuti\n4. Sudah terdokumentasi', 'Area 2', 'Berat', 4),
	(51, 51, 'KETUA', 'Pemanfaatan Ruang Tamu Terbuka sesuai  SEMA No. 3 Tahun 2010 dan Surat Edaran Dirjen Badilum No. 1 Tahun 2012', '1. Penataan ruang tamu terbuka terlihat\n    oleh umum \n2. Penerimaan tamu terkait penanganan\n    perkara harus dihadiri kedua belah pihak\n3. Penerimaan tamu terkait penanganan\n    perkara harus mengajukan permohonan\n    kepada Pimpinan Pengadilan\n4.Tamu bagi pejabat dan karyawan\n    Pengadilan yang tidak terkait perkara\n    wajib diterima di ruang tamu terbuka', 'Area 5,6\n', 'Sedang', 4),
	(52, 52, 'WAKIL KETUA', 'Pengawasan Implementasi Aplikasi SMART dan Aplikasi Monev Bappenas (PP 39 Tahun 2006)', '1. Pengisian tepat waktu per triwulan\n2. Memastikan seluruh komponen pada aplikasi\n    sudah terisi\n3. Sudah mengimplementasikan kedua\n    aplikasi tersebut dengan baik\n4. Melakukan evaluasi terhadap pelaksanaan\n   monitoring implementasi aplikasi (data dukung)', 'Area 4, 5', 'Berat', 4),
	(53, 53, 'WAKIL KETUA', 'Penanggungjawab pengawasan keakuratan dan ketepatan waktu pengisian data pada SIPP sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP serta pengunggahan putusan pada Direktori Putusan MA', '1. Memastikan Panmud dan Kimwasbid melaksanakan pengawasan dan uji petik terhadap data perkara pada SIPP setiap minggu\n2. Melakukan pembinaan dan pengawasan \n   mengenai anonimisasi pada putusan pengadilan  \n   yang dipublikasikan \n3. Melakukan pembinaan dan pengawasan mengenai pengunggahan \n   putusan pada Direktori Putusan\n4. Melaporkan hasil pelaksanaan monev akurasi data SIPP dan pengunggahan putusan pada DirPut setiap 6 (enam) bulan sekali kepada KPT', 'Area 2,5', 'Berat', 4),
	(54, 54, 'WAKIL KETUA', 'WKPN sebagai Koordinator Pengawasan', '1. Hakim pengawas bidang\n     melaksanakan tugas berdasarkan\n     SK dan ST KPN\n2. Sudah ada pedoman pelaksanaan\n    pengawasan bidang.\n3. WKPN sudah melaksanakan fungsinya\n     sebagai Koordinator Pengawasan\n     Hakim Bidang \n4. WKPN sudah membuat rencana dan\n     jadwal pengawasan\n5. Sudah dilakukan monitoring dan\n    evaluasi terhadap hasil pengawasan\n    bidang dan kinerja Hakim Pengawas\n    Bidang setiap bulan sekali\n6. Menindaklanjuti seluruh hasil evaluasi\n    terhadap laporan hasil pengawasan\n    bidang maupun tata cara pelaksanaan/kinerja\n   pengawasan (dengan data dukung)', 'Area 5', 'Berat', 6),
	(55, 55, 'WAKIL KETUA', 'Tugas Wakil Ketua Sebagai MR', '1.Sebagai penanggung jawab kegiatan internal\n    assesmen (data dukung notulen rapat dan\n    dokumen RTM)\n2. Memastikan sistem dokumentasi berjalan\n    dengan baik (melakukan monitoring terhadap\n    dokumen secara berkala)\n3. Melakukan evaluasi untuk menjamin dan\n    memastikan mutu dari proses APM (data\n    dukung)\n4. Membuat laporan kepada Ketua Tim APM\n    tentang kinerja tim APM dan kebutuhan\n    apapun untuk dikoreksi/perbaikan (data\n    dukung)', 'Area 2,5', 'Berat', 4),
	(56, 56, 'WAKIL KETUA / MR', 'Assesmen internal\n\n', '1. Sudah ada SK Tim Asesmen Internal\n2. Sudah membuat jadwal Assesmen dalam 1 tahun (minimal 2 kali per tahun)\n3.Sudah melaksanakan rapat persiapan\n   pelaksanaan Assesmen Internal\n4. Sudah ada rencana pelaksanaan untuk setiap\n    Assesmen Internal (yang memuat waktu\n    pelaksanaan, bagian yang diassesmen,nama\n    Assesor yang melaksanakan Assesmen)  \n5. Sudah ada daftar/list pertanyaan Assesmen\n    internal\n6. Assesmen Internal sudah dilakukan secara\n    silang\n7.Tindak lanjut hasil temuan sudah\n   dilaksanakan dan sesuai dengan SOP\n8. Tindak lanjut sudah dimonitoring dan evalusi\n    (dibuktikan dengan data dukung)\n9. Setiap pelaksanaan Assesmen Internal selalu\n    diakhiri dengan RTM\n10. Bertanggung jawab terhadap rekaman hasil\n     assesmen internal kepada Document Control\n     untuk dilakukan pengarsipan', 'Area 5\n', 'Berat', 10),
	(57, 57, 'HAKIM', 'Hakim Bertanggung Jawab Terhadap Minutasi Perkara', '1. Minutasi Tepat Waktu (14 hari untuk perkara perdata dan 7 hari untuk perkara pidana)\n2. E-doc putusan sudah diunggah ke SIPP\n3. Sudah dimonitoring dan evaluasi\n4. Sudah ditindaklanjuti (LHP, Buku Pengawasan Bidang, dan Notulen Rapat)', 'Area 2, 5\n', 'Berat', 4),
	(58, 58, 'HAKIM', 'Kewajiban Hakim untuk memonitor Berita Acara Sidang', '1. Seluruh Berita Acara Sidang sudah\n    diparaf dan ditandatangani\n2. Seluruh Berita Acara Sidang sudah diunggah\n    ke SIPP\n3. Seluruh Berita Acara Sidang sudah\n    digabungkan dan diarsipkan pada berkas\n    perkara\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti \n   (dibuktikan dengan data dukung)', 'Area 2, 5\n', 'Berat', 4),
	(59, 59, 'HAKIM', 'Hakim sudah menggunakan SIPP dalam administrasi perkara', '1. Penetapan hari sidang pertama\n    sudah dilaksanakan dengan\n    menggunakan SIPP\n2. Penetapan penahanan sudah\n    dilaksanakan dengan menggunakan\n    SIPP\n3. Perpanjangan Penahanan sudah\n    dilaksanakan dengan menggunakan\n    SIPP\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti  ', 'Area 2,5', 'Berat', 4),
	(60, 60, 'HAKIM', 'Hakim Bertanggung Jawab Terhadap Publikasi putusan pada Direktori Putusan dan kewajiban anonimisasi  putusan', '1. Selalu memastikan bahwa putusan perkara\n    yang ditangani sudah terpublikasikan pada\n    Direktori Putusan\n2. Memastikan putusan yang wajib anonimisasi\n    dipublikasikan sesuai SK KMA 1-\n    144/KMA/SK/I/2011\n3. Majelis setiap bulannya melakukan monitoring\n    terhadap publikasi seluruh putusannya pada\n    Direktori Putusan \n4. Majelis setiap bulannya melakukan monitoring\n    terhadap anonimisasi putusannya yang\n    dipublikasikan pada Direktori Putusan', 'Area 2,5,6', 'Berat', 4),
	(61, 61, 'HAKIM', 'Pengawasan Bidang', '1. Melakukan pengawasan setiap minggu \n2. Sudah ada data/keterangan hasil pengawasan pada buku pengawasan bidang yang dibuat oleh hakim terkait\n3.Membuat Laporan Hasil Pengawasan bidang setiap bulan dan format sudah seragam\n4.Sudah memonev tindaklanjut hasil pengawasan', 'Area 2,5', 'Berat', 4),
	(62, 62, 'HAKIM ', 'Hakim Pengawas dan Pengamat telah melakukan Pengawasan berkala sesuai aturan ( KUHAP dan SEMA No. 7 Tahun 1985) dan telah membuat laporan hasil pengawasan dan setiap laporan pengawasan sudah dievaluasi serta ditindaklanjuti, telah dilaporkan kepada Pengadilan Tingkat Banding', '1. Sudah ada SK penunjukkan Hakim\n     Pengawas dan Pengamat\n2. Sudah ada jadwal pengawasan\n3. Ada bukti laporan pengawasan\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti ', 'Area 2,5', 'Sedang', 4),
	(63, 63, 'HAKIM', 'Hakim wajib membuat penetapan penundaan sidang secara tertulis apabila jaksa penuntut umum tidak hadir di persidangan', '1. Selalu dilaksanakan dengan penetapan \n2.  Sudah dimonitoring\n3. Sudah dievaluasi\n4. Sudah ditindaklanjuti  \n    (dibuktikan dengan data dukung)', 'Area 2,5', 'Berat', 4),
	(64, 64, 'HAKIM', 'Court Calender', '1. Untuk perkara perdata court calender sudah \n    ditandatangani oleh para pihak\n2. Untuk perkara perdata sudah dibuat setelah \n    mediasi gagal \n3. Untuk perkara pidana court calender sudah \n    ditandantangani Hakim, Jaksa, Penasihat Hukum/\n    Terdakwa\n4. Untuk perkara Pidana dibuat sejak sidang \n    pertama.\n5. Court Calender yang sudah ditandatangani sudah  \n   diupload di SIPP untuk selanjutnya diarsipkan di \n   berkas', 'Area 2', 'Berat', 5),
	(65, 65, 'PANITERA', 'Pelaksanaan Delegasi berdasarkan SEMA Nomor 6 tahun 2014 tentang Penanganan Pemberitahuan /Panggilan dan Surat Edaran Dirjen Nomor 5 tahun 2019 tentang Peningkatan Kepatuhan Penanganan Bantuan Panggilan/Pemberitahuan Pada Pengadilan Negeri Pengaju', '1. Seluruh permintaan delegasi melalui SIPP\n2. Seluruh tahapan pada kolom delegasi SIPP\n    terinput secara tertib\n3. Bukti pembayaran dikirimkan bersamaan\n    surat permintaan Delegasi\n4. Monev dilakukan secara berkala setiap bulan dan \n    ditindaklanjuti\n5. Terhadap setiap permintaan bantuan yang belum \n    dilaksanakan oleh PN Pelaksana lebih dari 14 hari \n    maka PN wajib menyurati dengan tembusan kepada \n    KPT jika sudah menyurati dua kali belum juga ada \n    tindaklanjut dari PN Pelaksana maka disurati kembali \n    untuk yang ke tiga kali dengan tembusan kepada \n    Badan Pengawasan', 'Area 2, 5, 6\n', 'Berat', 5),
	(66, 66, 'PANITERA', 'Pelaksanaan Delegasi berdasarkan SEMA Nomor 6 tahun 2014 tentang Penanganan Pemberitahuan /Panggilan dan Surat Edaran Dirjen Nomor 5 tahun 2019 tentang Peningkatan Kepatuhan Penanganan Bantuan Panggilan/Pemberitahuan Pada Pengadilan Negeri Pelaksana', '1. Seluruh tahapan pada kolom delegasi SIPP\n     terinput secara tertib\n2. Seluruh pelaksanaan delegasi Panggilan atau\n    pemberitahuan tidak melampaui 14 hari\n3. Dokumen relaas diupload ke SIPP maksimal 1 hari \n    setelah pelaksanaan relaas\n4. Dokumen fisik dikirimkan ke PN Pengaju\n    paling lambat pada hari berikutnya setelah\n    pengiriman dokumen secara elektronik\n5. Monev dilakukan secara berkala setiap bulan\n6. Hasil Monev sudah ditindaklanjuti\n7. Pelaksanaan sudah didokumentasikan\n    dengan baik', 'Area 2, 5, 6\n', 'Berat', 7),
	(67, 67, 'PANITERA', 'Pelaksanaan Rapat evaluasi kinerja pada Kepaniteraan', '1. Ada rapat rutin bulanan yang dimulai secara\n     berjenjang dari satuan terkecil (Panmud\n     masing-masing) didampingi Hakim Pengawas\n     Bidang dan dibuktikan dengan notulen rapat\n2. Ada monitoring dan evaluasi capaian kinerja,  \n    pencatatan keuangan perkara dan kedisiplinan \n    pengisian data pada SIPP setiap bulan\n3. Ada tindak lanjut dari hasil evaluasi\n4. Terdokumentasi dengan baik', 'Area 2, 5', 'Berat', 4),
	(68, 68, 'PANITERA', 'Panjar Biaya Perkara \n(Surat Dirjen Badilum Nomor 613/DJU/PS.01/6/2020 tentang Pedoman kepatuhan pemberitahuan pengembalian sisa panjar biaya perkara)', '1. Panitera memastikan bahwa surat pengembalian sisa panjar kepada pihak sudah dikirimkan maksimal 5 (lima) hari kerja setelah tanggal minutasi\n2. Panitera memastikan bahwa seluruh sisa panjar biaya perkara yang sudah diberitahukan kepada pihak, sudah dikembalikan dalam jangka waktu 6 (enam) bulan terhitung sejak tanggal surat pemberitahuan\n3.Seluruh sisa panjar perkara yang sudah melewati 6 (enam) bulan dan tidak diambil pihak setelah diberitahukan harus segera disetorkan ke Kas Negara\n4.Panitera memastikan Panmud Perdata melakukan Monev pengembalian sisa panjar biaya perkara secara berkala dan melaporkan kepada panitera setiap bulannya', 'Area 2, 5, 6\n', 'Berat', 4),
	(69, 69, 'PANMUD PIDANA', 'Pencatatan surat masuk/keluar', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', 'Area 2', 'Ringan', 4),
	(70, 70, 'PANMUD PIDANA', 'Adanya uraian Tugas masing-masing unit', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', 'Area 2,5', 'Sedang', 4),
	(71, 71, 'PANMUD PIDANA', 'Implementasi SOP', '1. KPN sudah menetapkan SK tentang\n    pemberlakuan SOP yang dikeluarkan\n    oleh Dirjen Badilum\n2. Sudah dilaksanakan (uji petik\n    minimal 5 kegiatan) \n3. Sudah dilakukan monitoring dan evaluasi\n4. Sudah melaporkan hasil monev kepada Ditjen\n    Badilum minimal satu tahun sekali', 'Area 2,5', 'Berat', 4),
	(72, 72, 'PANMUD PIDANA', 'Pelaksanaan monitoring/pengawasan, evaluasi terhadap keakuratan dan ketepatan waktu pengisian data pada SIPP dan Tindak lanjut hasil pengawasan pada panmud pidana sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP', '1. Dilakukan 1x setiap minggu\n2.  Melaporkan setiap bulan kepada KPN setelah divalidasi oleh panitera\n3. Menindaklanjuti hasil monev yang dilakukan panmud dan seluruh temuan dari pengawasan bidang\n4. Terdokumentasi/tercatat', 'Area 2,5', 'Berat', 4),
	(73, 73, 'PANMUD PIDANA', 'Penomoran perkara dan template putusan sudah sesuai dengan SK KMA No. 44 Tahun 2014', '1. Penomoran perkara sudah sesuai dengan SK\n     KMA No. 44 Tahun 2014\n2. Template putusan sudah sesuai dengan SK\n    KMA No. 44 Tahun 2014\n3. Template putusan sudah menggunakan SIPP\n4. Sudah dimonev (misal : objek pemeriksaan pengawasan bidang)', 'Area 2,5\n', 'Berat', 4),
	(74, 74, 'PANMUD PIDANA', 'Penyerahan berkas perkara inactive dari Panmud Pidana kepada Panmud Hukum harus dengan Berita Acara Serah Terima Berkas ( dalam jangka waktu 3 hari setelah BHT )\n', '1. Selalu dilaksanakan\n2. Dilaksanakan tepat waktu\n3. Sudah menggunakan Berita Acara\n4. Sudah diarsipkan dan diinput dalam SIPP', 'Area 2', 'Sedang', 4),
	(75, 75, 'PANMUD PIDANA', 'Pemberkasan Arsip Perkara yang telah diminutasi sudah sesuai dengan SK Direktur Jenderal Badan Peradilan Umum No. 1939/DJU/SK/HM.02.3/10/2018', '1. Susunan Berkas Perkara sudah tepat\n2. Penjilidan Sudah sesuai ketentuan (warna\n    sampul, checklist, dijahit sesuai ketentuan,\n    dan menggunakan laks)\n3. Format Checklist sudah tepat\n4. Format Court Calender sudah tepat\n5. Sudah dilakukan monitoring dan evaluasi', 'Area 2,5', 'Sedang', 5),
	(76, 76, 'PANMUD PIDANA', 'Penggunaan Dokumen Elektronik untuk pengajuan upaya hukum Kasasi dan PK sesuai SEMA No 1 Tahun 2014', '1. Seluruh pengajuan upaya hukum Kasasi dan PK sudah \n     melalui Direktori Putusan \n2. KPN sudah membuat SOP Upaya Hukum Kasasi dan\n   PK dengan Dokumen Elektronik\n3. Dokumen Elektronik yang dikirimkan sudah lengkap \n    (uji petik) \n4. Sudah dimonev', 'Area 2,5', 'Berat', 4),
	(77, 77, 'PANMUD PIDANA', 'Kelengkapan Berkas Banding', '1. Berkas yang dikirim ke PT sudah lengkap\n     sesuai dengan ketentuan Buku II \n2. Maksimal 14 hari berkas sudah diterima\n    Pengadilan Tinggi (236 KUHAP)\n3. Terdata dalam SIPP \n4. Sudah dimonev                                                                                               ', 'Area 2,5', 'Berat', 4),
	(78, 78, 'PANMUD PIDANA', 'Kelengkapan Berkas Kasasi (Manual)', '1. Berkas yang dikirim ke Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II \n2. Untuk laporan kasasi, penahanan maksimum\n    3 hari sejak adanya permohonan kasasi,\n    harus sudah dilaporkan ke Mahkamah Agung\n3. Berkas perkara permohonan kasasi (ditahan)\n    paling lambat 3 hari setelah memori kasasi\n    diterima, dikirimkan ke Mahkamah Agung\n4. Berkas perkara permohonan kasasi (tidak\n    ditahan ) paling lambat 30 hari setelah memori\n    kasasi diterima, dikirimkan ke Mahkamah\n    Agung\n5. Ceklis kelengkapan berkas kasasi \n6. Penginputan kedalam aplikasi SIPP dilakukan\n   1x24 jam\n\n', 'Area 2', 'Berat', 6),
	(79, 79, 'PANMUD PIDANA', 'Kelengkapan Berkas PK (Manual)', '1. Berkas yang diterima Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II \n2. Kepatuhan waktu dalam pengiriman berkas\n    peninjuan kembali ke Mahkamah Agung\n    dalam waktu maksimal 30 hari setelah\n    Pemeriksaan Persidangan (PIDANA) \n3. Penginputan ke dalam aplikasi SIPP\n    dilakukan 1x24 jam\n4. Ceklis kelengkapan berkas PK', 'Area 2', 'Berat', 4),
	(80, 80, 'PANMUD PIDANA', 'Permohonan kasasi yang telah memenuhi syarat formal selambat lambatnya dalam waktu 14 hari setelah tenggang waktu mengajukan memori kasasi berakhir, berkas kasasi harus sudah dikirim ke Mahkamah Agung (Buku II)', 'Berkas sudah dikirim tepat waktu dan lengkap ke Mahkamah Agung', 'Area 2', 'Berat', 1),
	(81, 81, 'PANMUD PIDANA', 'Kepatuhan PN dalam pelaksanaan :\n1. SEMA 1 Tahun 1987 tentang pengiriman berkas perkara pidana yang terdakwanya berada dalam tahanan\n2. SEMA 3 Tahun 1987 tentang permohonan penetapan penahanan oleh MA bagi terdakwa yang berada dalam tahanan\n3. SEMA 2 Tahun 1998 tentang permohonan kasasi perkara pidana yang terdakwanya berada dalam status tahanan\n4. Surat Panitera MA Nomor 2304/PAN/HK.01/12/2020 tentang Prosedur penyampaian laporan kasasi dan berkas perkara pidana yang Terdakwanya berada dalam status tahanan', '1. Membuat laporan kasasi perkara pidana yang \n    terdakwanya berada dalam tahanan dengan tepat\n    waktu yakni 3 (hari) kerja terhitung sejak diterimanya \n    permohonan kasasi dari Terdakwa/Jaksa Penuntut \n    Umum\n2. Laporan tersebut disampaikan melalui aplikasi \n    Direktori Putusan MA jika Direktori Putusan MA sedang \n    bermasalah maka dapat melalui email ke   \n   kepaniteraan@mahkamahagung.go.id dan \n   kepaniteraan.mari@gmail.com\n3. Berkas kasasi (Bundel A dan B) perkara pidana yang \n   terdakwanya berada dalam tahanan telah diterima oleh  \n   Mahkamah Agung paling lama 30 (tiga puluh) hari \n   kalender terhitung sejak diajukannya permohonan \n   kasasi\n4. Penyampaian laporan kasasi menggunakan format \n   yang ditentukan dalam SEMA Nomor 2 Tahun 1998\n5. Memberikan \'tanda\' tahanan pada sampul berkas kasasi \n   yang menunjukan bahwa terdakwanya ditahan\n', 'Area 2', 'Berat', 5),
	(82, 82, 'PANMUD PERDATA', 'Pencatatan surat masuk/keluar', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', 'Area 2', 'Ringan', 4),
	(83, 83, 'PANMUD PERDATA', 'Adanya uraian Tugas masing-masing unit', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', 'Area 2,5', 'Sedang', 4),
	(84, 84, 'PANMUD PERDATA', 'Implementasi SOP', '1. SOP yang dikeluarkan sudah disosialisasikan\n    oleh Dirjen Badilum\n2. Sudah dilaksanakan (uji petik\n    minimal 5 kegiatan) \n3. Sudah dilakukan monitoring dan evaluasi\n4. Sudah melaporkan hasil monev kepada Ditjen\n    Badilum minimal satu tahun sekali', 'Area 2,5', 'Berat', 4),
	(85, 85, 'PANMUD PERDATA', 'Pelaksanaan monitoring/pengawasan, evaluasi terhadap keakuratan dan ketepatan waktu pengisian data pada SIPP dan Tindak lanjut hasil pengawasan pada panmud Perdata sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP', '1. Dilakukan 1x setiap minggu\n2.  Melaporkan setiap bulan kepada KPN setelah divalidasi oleh panitera\n3. Menindaklanjuti hasil monev yang dilakukan panmud dan seluruh temuan dari pengawasan bidang\n4. Terdokumentasi/tercatat', 'Area 2,5', 'Berat', 4),
	(86, 86, 'PANMUD PERDATA', 'Pemberkasan Arsip Perkara yang telah diminutasi sudah sesuai dengan SK Direktur Jenderal Badan Peradilan Umum No. 1939/DJU/SK/HM.02.3/10/2018', '1. Susunan Berkas Perkara sudah tepat\n2. Penjilidan Sudah sesuai ketentuan (warna\n    sampul, checklist, dijahit sesuai ketentuan,\n    dan menggunakan laks)\n3. Format Checklist sudah tepat\n4. Format Court Calender sudah tepat\n5. Sudah dilakukan monitoring dan evaluasi', 'Area 2,5', 'Sedang', 5),
	(87, 87, 'PANMUD PERDATA', 'Penomoran perkara dan template putusan sudah sesuai dengan SK KMA No. 44 Tahun 2014', '1. Penomoran perkara sudah sesuai dengan SK\n     KMA No. 44 Tahun 2014\n2. Template putusan sudah sesuai dengan SK\n    KMA No. 44 Tahun 2014\n3. Template putusan sudah menggunakan SIPP\n4. Sudah dimonev (misal : objek pemeriksaan pengawasan bidang)', 'Area 2,5\n', 'Berat', 4),
	(88, 88, 'PANMUD PERDATA', 'Penyerahan berkas perkara inactive dari Panmud Perdata kepada Panmud Hukum harus dengan Berita Acara Serah Terima Berkas ( dalam jangka waktu 3 hari setelah BHT )', '1. Selalu dilaksanakan tepat waktu 3 hari\n    setelah BHT\n2. Sudah menggunakan Berita Acara\n3. Sudah diarsipkan\n4. Sudah diinput dalam SIPP dengan tepat waktu', 'Area 2', 'Sedang', 4),
	(89, 89, 'PANMUD PERDATA', 'Pelaporan Keuangan Perkara dan Komdanas', '1. Sudah menggunakan aplikasi pelaporan Keuangan Perkara serta Penginputan data  pada aplikasi komdanas secara tepat dan tertib setiap bulan\n2. Pelaporan dilakukan mulai dari tanggal 1 sd  5 setiap bulannya (SEMA Nomor 4 Tahun 2018)\n3. Pengiriman dokumen lengkap sesuai aturan\n4. Pimpinan melakukan monitoring dan evaluasi per bulan\n5. Penutupan register sudah dilakukan secara tertib dan ditandatangani \n', 'Area 4,5', 'Berat', 5),
	(90, 90, 'PANMUD PERDATA', 'Surat Kuasa Untuk Membayar (SKUM)', '1. Perhitungan panjar sudah dilakukan secara\n     otomatis\n2. SKUM sudah diberi Nomor (bukan nomor\n    perkara)\n3. Pembayaran melalui Bank / multi chanel\n4. Terdokumentasi dengan baik', 'Area 2', 'Berat', 4),
	(91, 91, 'PANMUD PERDATA', 'Penggunaan Dokumen Elektronik untuk pengajuan upaya hukum Kasasi dan PK sesuai SEMA No 1 Tahun 2014', '1. Seluruh pengajuan upaya hukum Kasasi dan PK sudah \n     melalui Direktori Putusan \n2. KPN sudah membuat SOP Upaya Hukum Kasasi dan\n   PK dengan Dokumen Elektronik\n3. Dokumen Elektronik yang dikirimkan sudah lengkap \n    (uji petik) \n4. Sudah dimonev', 'Area 2,5', 'Berat', 4),
	(92, 92, 'PANMUD PERDATA', 'Kelengkapan Berkas Banding', '1. Berkas yang dikirim ke PT sudah lengkap\n     sesuai dengan ketentuan Buku II \n2. Maksimal 30 hari berkas sudah diterima\n    Pengadilan Tinggi   \n3. Terinput dalam SIPP \n4. Terdokumentasi dengan baik                                                                                               ', 'Area 2', 'Berat', 4),
	(93, 93, 'PANMUD PERDATA', 'Kelengkapan Berkas Kasasi (Manual)', '1. Permohonan kasasi yang telah memenuhi\n     syarat formal selambat lambatnya dalam\n     waktu 14 hari setelah tenggang waktu\n     mengajukan memori kasasi berakhir, berkas\n     kasasi harus sudah dikirim ke Mahkamah Agung\n2.  Berkas yang diterima Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II dan SEMA 1 Tahun 2014 (termasuk \n     dokumen elektronik)\n3.Penginputan ke dalam aplikasi SIPP\n    dilakukan 1x24 jam\n4. Ceklis kelengkapan berkas Kasasi', 'Area 2', 'Berat', 4),
	(94, 94, 'PANMUD PERDATA', 'Kelengkapan Berkas PK (Manual)', '1. Berkas yang diterima Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II \n2. Kepatuhan waktu dalam pengiriman berkas\n    peninjauan kembali ke Mahkamah Agung\n    dalam waktu maksimal 30\n    hari setelah Jawaban/tanggapan atas alasan\n    PK (PERDATA)\n3. Penginputan ke dalam aplikasi SIPP\n    dilakukan 1x24 jam\n4. Ceklis kelengkapan berkas PK', 'Area 2', 'Berat', 4),
	(95, 95, 'PANMUD HUKUM', 'Pencatatan surat masuk/keluar', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', 'Area 2', 'Ringan', 4),
	(96, 96, 'PANMUD HUKUM', 'Adanya uraian Tugas masing-masing unit', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', 'Area 2,5', 'Sedang', 4),
	(97, 97, 'PANMUD HUKUM', 'Implementasi SOP', '1. KPN sudah menetapkan SK tentang\n    pemberlakuan SOP yang dikeluarkan\n    oleh Dirjen Badilum\n2. Sudah dilaksanakan (uji petik\n    minimal 5 kegiatan) \n3. Sudah dilakukan monitoring dan evaluasi\n4. Sudah melaporkan hasil monev kepada Ditjen\n    Badilum minimal satu tahun sekali', 'Area 2,5', 'Berat', 4),
	(98, 98, 'PANMUD HUKUM', 'Pelaksanaan monitoring/pengawasan, evaluasi terhadap keakuratan dan ketepatan waktu pengisian data pada SIPP dan Tindak lanjut hasil pengawasan pada panmud hukum sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP', '1. Dilakukan 1x setiap minggu\n2.  Melaporkan setiap bulan kepada KPN setelah divalidasi oleh panitera\n3. Menindaklanjuti hasil monev yang dilakukan panmud dan seluruh temuan dari pengawasan bidang\n4. Terdokumentasi/tercatat', 'Area 2,5', 'Berat', 4),
	(99, 99, 'PANMUD HUKUM', 'Prosedur tata kelola arsip (lakukan uji petik, minimal 10 berkas)', '1. Sudah menggunakan aplikasi SIPP\n2. Penataan berkas sudah sesuai\n     dengan penataan aplikasi SIPP\n3. Setiap pencarian berkas dapat\n     ditemukan kurang dari 5 menit\n4. Ada jadwal perawatan arsip\n5. Ruang arsip dilengkapi komputer', 'Area 2', 'Sedang', 5),
	(100, 100, 'PANMUD HUKUM', 'Prosedur Peminjaman Berkas', '1. Sudah ada SOP Peminjaman berkas oleh internal dan external\n2. Peminjaman berkas disetujui oleh panitera dan diketahui oleh Ketua Pengadilan\n3. Sudah ditetapkan batas waktu\n     peminjaman\n4. Peminjaman berkas tercatat dengan\n    baik', 'Area 2,5', 'Sedang', 4),
	(101, 101, 'PANMUD HUKUM', 'Pelaporan perkara secara elektronik', '1. Telah melaksanakan pelaporan\n     perkara secara lengkap sesuai\n     dengan SK Dirjen Badilum Nomor\n     2992/DJU/SK/HM.02.3/9/2019\n2.Telah melaksanakan pelaporan perkara tepat waktu\n    sesuai dengan SK Dirjen Badilum\n    Nomor 2992/DJU/SK/HM.02.3/9/2019 \n3. Data yang dikirimkan akurat dan dapat \n    dipertanggungjawabkan\n4. Telah dimonev', 'Area 2,5', 'Sedang', 4),
	(102, 102, 'PANMUD HUKUM', 'Survey kepuasan masyarakat berdasarkan PERMENPAN No. 14 Tahun 2017 dan SK Dirjen Badilum No.1230/DJU/SK/HM.02.3/4/2021\n', '1. Ada Tim survey\n2.Survey menggunakan aplikasi SISUPER dari Ditjen Badilum\n3. Survey dilakukan 4 kali setahun (per Triwulan)\n4. Laporan Hasil Survey sudah di monev (3 unsur terendah)\n5. Hasil evaluasi sudah  ditindaklanjuti\n6. Hasil survey sudah terpublikasi (website\n    dan di ruang PTSP)', 'Area 6', 'Berat', 6),
	(103, 103, 'PANMUD HUKUM', 'Pelaksanaan Survey Persepsi Anti Korupsi berdasarkan SK Dirjen Badilum No.1230/DJU/SK/HM.02.3/4/2021', '1. Ada Tim survey\n2.Survey menggunakan aplikasi SISUPER dari Ditjen Badilum\n3. Survey dilakukan 4 kali setahun\n4. Laporan Hasil Survey sudah di monev (3 unsur terendah)\n5. Hasil evaluasi sudah  ditindaklanjuti\n6. Hasil survey sudah terpublikasi (website\n    dan di ruang PTSP)', 'Area 6', 'Berat', 6),
	(104, 104, 'PANMUD HUKUM', 'Pelaksanaan Survey Harian berdasarkan SK Dirjen Badilum No.1230/DJU/SK/HM.02.3/4/2021', '1. Ada Tim survey\n2. Survey menggunakan aplikasi SISUPER dari\n    Ditjen Badilum\n3. Survey dilakukan setiap hari kerja\n4. Hasil survey direkap setiap bulan\n5. Hasil evaluasi digunakan untuk bahan\n    pemberian reward and punishment untuk\n    petugas ptsp', 'Area 6\niv.a', 'Berat', 5),
	(105, 105, 'PANMUD HUKUM', 'Monitoring Pelaksanaan Tugas Posbakum', '1. Melakukan pelaporan setiap bulan\n     kepada Ditjen Badilum terdiri dari\n     Laporan Jumlah, Jenis konsultasi,\n    waktu layanan dan jenis kelamin\n    yang dibantu melalui POSBAKUM\n2. Pelaporan sudah menggunakan\n    aplikasi\n3. Panmud Hukum melakukan monitoring secara \n    berkala terhadap Posbakum untuk memastikan bahwa \n    posbakum melaksanakan tugasnya dan tidak \n    melakukan larangan sebagaimana dalam peraturan \n    Perma No 1 Tahun 2014\n4. Panmud Hukum melakukan evaluasi\n    terhadap kinerja Posbakum setiap\n    tahun', 'Area 5,6', 'Sedang', 4),
	(106, 106, 'PANMUD HUKUM', 'Posbakum', '\n1. Adanya MoU antara Ketua Pengadilan\n    dengan Lembaga Layanan Bantuan\n    Hukum dan diperbarui setiap tahun\n2. Absensi Petugas POSBAKUM\n3. Jadwal Piket petugas POSBAKUM\n4. Buku tamu\n5. Daftar pengacara yang dapat\n    dihubungi untuk perkara prodeo\n6. Ada informasi layanan tanpa dipungut\n    biaya yang terpublikasi\n7. Tidak boleh ada identitas OBH pada\n    ruang Posbakum (Spanduk, Banner,\n    Logo)\n8. Kops Surat OBH tidak menggunakan\n    alamat pengadilan', 'Area 6', 'Sedang', 8),
	(107, 107, 'PANITERA PENGGANTI', 'Mengerjakan minutasi perkara sesuai SOP', '1. Minutasi selesai maksimal 7 hari untuk perkara pidana \n     dan 14 hari perkara perdata setelah putusan\n2. Tanggal putusan diinput ke SIPP 1 x 24 jam\n    sejak tanggal putusan\n3. Amar putusan diinput ke SIPP 1 x 24 jam sejak\n    tanggal putusan\n4. Mengunggah dokumen putusan ke SIPP 1 x 24\n     jam sejak tanggal putusan', 'Area 2', 'Sedang', 4),
	(108, 108, 'PANITERA PENGGANTI', 'Kewajiban PP untuk membuat berita acara sidang, 1 hari sebelum hari sidang berikutnya, harus sudah selesai dan ditandatangani', '1. Berita Acara Sidang sudah selesai 1 hari\n     sebelum hari sidang berikutnya\n2. Sudah diparaf tiap lembarnya dan BA sudah\n    ditandatangani \n3. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti \n   (dibuktikan dengan data dukung)\n4. Berita Acara sudah diupload kedalam\n   aplikasi SIPP', 'Area 2,5', 'Berat', 4),
	(109, 109, 'PANITERA PENGGANTI', 'Penundaan sidang pada SIPP oleh PP', '1.Penundaan sidang sudah diinput secara\n   lengkap kedalam SIPP\n2. Penginputan kedalam SIPP sudah 1x24 jam\n', 'Area 2', 'Berat', 2),
	(110, 110, 'PANITERA PENGGANTI', 'Kesesuaian SIPP dengan proses yang berlangsung', '1.Pengisian pada SIPP sudah sesuai dengan\n    pemberkasan hardcopynya pada setiap\n    tahapannya (uji petik minimal 10 berkas)\n2. Panmud Pidana telah melakukan monev\n3. Panmud Perdata telah melakukan monev\n4. Hasil Monev sudah ditindaklanjuti', 'Area 2,5', 'Berat', 4),
	(111, 111, 'JURUSITA/JURUSITA PENGGANTI', 'Permintaan Delegasi Bantuan Panggilan/Pemberitahuan (PN Pengaju)', '1.Bukti biaya pengiriman selalu dikirimkan\n    bersamaan dengan permintaan\n2. Data permintaan delegasi diisi lengkap dan\n    tertib pada SIPP\n3. Kelengkapan dokumen selalu diunggah dan\n    dikirimkan melalui SIPP \n4.Memonitor setiap permintaan delegasi keluar dan melaporkan setiap minggu kepada Panitera', 'Area 2,5,6', 'Sedang', 4),
	(112, 112, 'JURUSITA/JURUSITA PENGGANTI', 'Pelaksanaan Delegasi Bantuan Panggilan/Pemberitahuan (PN Pelaksana)', '1.Jurusita/Jurusita Pengganti mengajukan\n    pencairan anggaran kepada kepada koordinator   \n    delegasi setelah ada Surat Tugas\n2. Jurusita/Jurusita Pengganti menyampaikan\n     relaas kepada Pihak maksimal dua hari sejak surat  \n    tugas diterima\n3. Jurusita/Jurusita Pengganti menyampaikan\n    Relaas pemanggilan/pemberitahuan yang\n   telah dilaksanakan, pada hari yang sama\n   dengan pelaksanaan kepada koordinator\n   delegasi\n4. Jurusita/Jurusita Pengganti selalu memberikan\n    bukti pemanggilan/pemberitahuan kepada\n    Koordinator delegasi sebagai pertanggungjawaban', 'Area 2,5,6', 'Sedang', 4),
	(113, 113, 'JURUSITA/JURUSITA PENGGANTI', 'Pengiriman Bukti Delegasi Pemanggilan/Pemberitahuan yang telah dilaksanakan (PN Pelaksana)', '1. Koordinator Delegasi/Jurusita/Jurusita\n    Pengganti melakukan pemindaian/scanning\n    relaas pemanggilan/pemberitahuan \n2. Koordinator Delegasi/Jurusita/Jurusita\n    Pengganti mengunggah ke aplikasi SIPP maksimal \n    pada hari berikutnya setelah penyerahan Relaas\n    dari Jurusita/Jurusita Pengganti\n3. Asli Relaas pemanggilan/pemberitahuan\n    dikirimkan paling lama satu hari setelah\n    koordinator menerima relaas dari Jurusita/\n    Jurusita Pengganti\n4. Koordinator Delegasi/Jurusita/Jurusita\n    Pengganti melakukan pengisian data/\n    informasi termasuk tanggal pelaksanaan, pada \n    aplikasi SIPP', 'Area 2', 'Sedang', 4),
	(114, 114, 'SEKRETARIS', 'Persidangan Elektronik', '1. Memastikan jaringan internet mendukung pelaksanaan persidangan elektronik\n2.Memastikan ketersediaan sarana prasarana persidangan elektronik sesuai dengan SK Dirjen Nomor 1693/DJU/SK/HM02.3/12/2020\n3.Minimal 1 (satu) ruang persidangan sudah dilengkapi dengan Fasilitas sebagaimana nomor 2\n4.Memastikan sarana prasarana tersebut dalam kondisi baik dan terpelihara ', 'Area 2', 'Sedang', 4),
	(115, 115, 'SEKRETARIS', 'Sekretaris melakukan rapat evaluasi kinerja pegawai ', '1. Ada rapat rutin bulanan yang dimulai secara\n     berjenjang dari satuan terkecil (Kasub\n     masing-masing) dibuktikan dengan notulen rapat\n2. Ada monitoring dan evaluasi capaian kinerja berdasarkan PKP/PCK dan LLK\n3. Ada tindak lanjut dari hasil evaluasi\n4. Terdokumentasi dengan baik', 'Area 3,5', 'Berat', 4),
	(116, 116, 'SEKRETARIS', 'Implementasi RINGKAS 5R', '1.Sudah diterapkan di seluruh bagian (Hakim, Kepaniteraan dan Kesekretariatan)                                                  2.Penataan barang / alat kerja sudah\n   dipisah-pisahkan antara yang jarang\n   dipakai dan sering dipakai\n3. menyingkirkan barang yang tidak\n    diperlukan\n4. Sudah dilakukan monev dan ditindaklanjuti', 'Area 1,5', 'Ringan', 4),
	(117, 117, 'SEKRETARIS', 'Implementasi RAPI 5R', '1. Sudah diterapkan di seluruh bagian (Hakim, Kepaniteraan dan Kesekretariatan)                                                   2. Penyimpanan barang/ alat sesuai tempat\n    yang telah ditentukan, \n3. Sudah diberi label \n4. Setiap pegawai pada saat datang dan\n    sebelum pulang harus merapikan dan\n    menyimpan berkas kerja ditempat yang\n    telah disediakan\n5. Sudah dilakukan monev dan ditindaklanjuti', 'Area 1,5', 'Ringan', 5),
	(118, 118, 'SEKRETARIS', 'Implementasi RESIK 5R', '1. Kebersihan pada tempat kerja/lingkungan kerja terjaga\n2. Kebersihan Peralatan kerja terjaga\n3. Sudah diterapkan di seluruh bagian\n4. Sudah dilakukan monev dan ditindaklanjuti', 'Area 1,5', 'Ringan', 4),
	(119, 119, 'SEKRETARIS', 'Implementasi RAWAT 5R', 'Sudah membakukan/ menetapkan standar untuk mempertahankan 3 R (Rapi,Ringkas,Resik) yaitu dengan menetapkan :\n1. Cara pengendalian, \n2. Mekanisme pemantauan, \n3. Pemeriksaan berkala\n4. Pola tindak lanjut ', 'Area 1,5', 'Ringan', 4),
	(120, 120, 'SEKRETARIS', 'Implementasi RAJIN 5R', '1. Seluruh bagian sudah mengimplementasikan Ringkas dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n2. Seluruh bagian sudah mengimplementasikan Rapi dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n3. Seluruh bagian sudah mengimplementasikan Resik dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n4. Seluruh bagian sudah mengimplementasikan Rawat dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n', 'Area 1,5', 'Ringan', 4),
	(121, 121, 'SEKRETARIS', 'Sarana dan Prasarana untuk layanan Disabilitas di Pengadilan \nsesuai SK Dirjen No 1692/DJU/SK/PS.00/12/2020', '1. Tersedia Parkir khusus Disabilitas                                                 \n2. Jalur Guiding Block dan warning Block menuju gedung dan ruangan di pengadilan\n3. Ramp/Jalur Landai\n4.Alat bantu mobilitas (kursi roda dan tongkat), alat bantu dengar\n5.Kursi tunggu Disabilitas\n6.Tempat yang disediakan khusus untuk pengguna kursi roda pada pelayanan PTSP, ruang sidang dan layanan publik lainnya \n7. Ruang sidang ramah disabilitas\n8. Ruang kesehatan yang dapat digunakan sebagai ruang bagi penyandang disabilitas Intelektual\n9. Tersedia daftar pendamping/pembimbing, penerjemah dan petugas lain yang terkait \n10. Sudah ada petugas yang mengikuti pelatihan disabilitas\n11.Sudah ada papan informasi visual\n12. Toilet khusus Disabilitas (tinggi toilet, pegangan rambat, tombol darurat)\n13. Sudah ada media informasi braile\n14. Website pengadilan sudah dilengkapi screen reader', 'Area 6\n', 'Sedang', 14),
	(122, 122, 'SEKRETARIS', 'Sekretaris melakukan rapat evaluasi anggaran per triwulan dan menyampaikan Laporan Realisasi Anggaran ( LRA ) tiap bulan kepada KPT', '1. Sekretaris melaporkan secara tertulis\n    setiap bulan kepada KPT\n2. Sudah dilakukan secara tertib setiap\n    triwulan                                                                      \n3. Pelaksanaan sudah dimonitoring,\n    evaluasi \n4. Sudah ditindaklanjuti\n5.Terdokumentasi dengan baik', 'Area 4,5', 'Sedang', 5),
	(123, 123, 'SEKRETARIS', 'Sekretaris selaku Kuasa Pengguna Barang (KPB) membuat laporan persemester dan tahunan terhadap Barang Milik Negara (BMN) ke Badan Urusan Administrasi MA (DIPA 01) dan Badilum (DIPA 03)', '1. Sudah dilakukan secara tertib setiap\n     persemester \n2. Sudah dilakukan secara tertib setiap tahunan\n3. Pelaksanaan sudah dimonitoring, evaluasi\n    dan ditindaklanjuti\n4. Terdokumentasi dengan baik', 'Area 4,5', 'Sedang', 4),
	(124, 124, 'SEKRETARIS', 'Sekretaris selaku Kuasa Pengguna Barang (KPB) membuat laporan pengawasan dan pengendalian BMN ke Kantor Pelayanan Kekayaan Negara Lelang (KPKNL) ', '1.  Sudah dilakukan secara tertib dan berkala\n2. Pelaksanaan sudah dimonitoring, evaluasi \n3. Sudah ditindaklanjuti\n4. Terdokumentasi dengan baik', 'ETARISoen 2', 'Berat', 4),
	(125, 125, 'SEKRETARIS', 'Sekretaris selaku Kuasa Pengguna Barang (KPB) mengusulkan penetapan status penggunaan BMN ke Sekretaris MA cq Kepala Biro Perlengkapan', '1. Sudah mengusulkan secara tertulis, tertib\n    dan berkala\n2. Terdokumentasi dengan baik\n3. Sudah dilakukan Monev\n4. Sudah ditindaklanjuti', 'Area 4,5', 'Sedang', 4),
	(126, 126, 'SEKRETARIS', 'Tugas Document Control/ Pengendalian Dokumen (DC)', '1. Melakukan penyimpanan arsip hasil\n    kegiatan APM dan ZI (Dokumen tertata dengan\n    baik)\n2. Melakukan pengendalian terhadap\n    kesesuaian dokumen yang beredar\n3. Menjadi pusat data dokumentasi tim APM\n4. Memastikan kecukupan dokumentasi\n    (formulir-formulir APM yang dikeluarkan\n    oleh Ditjen Badilum)\n5. Membuat laporan kepada QMR tentang\n    kegiatan dokumentasi tim APM', 'Area 2', 'Berat', 5),
	(127, 127, 'SEKRETARIS', 'Kelengkapan Document pada Document Control', 'Kelengkapan dokumen Akreditasi dan Zona Integritas\n1. Dokumen tertata dengan baik \n2. List daftar master dokumen\n3. Bukti Distribusi dokumen\n4. Penomoran dokumen\n5. Penggunaan stamp "terkendali", "tidak\n    terkendali" dan "kadaluarsa"', 'Area 2', 'Sedang', 5),
	(128, 128, 'SEKRETARIS', 'Pengadaan Barang dan Jasa (SK PPK, SK Pejabat Pengadaan dan SK Petugas penyimpan BMN)', '1. Seluruh SK sudah ditetapkan dan tepat\n     sesuai Perpres No 16 Tahun 2018\n2. SK sudah diperbaharui setiap tahun\n3. Sudah di Monev\n4. Sudah Terdokumentasi dengan baik', 'Area 4,5,6', 'Berat', 4),
	(129, 129, 'SEKRETARIS', 'Tim Pengelola Website', '1. Ada SK Tim Pengelola Website yang mengatur\n    Tata Cara pengelolaan website dan ditetapkan\n    oleh Ketua Pengadilan Negeri\n2. Memastikan isi website selalu diperbaharui\n3. Memahami keterbukaan informasi publik\n4. Melakukan monev secara berkala (data\n    dukung)', 'Area 2,5,6', 'Sedang', 4),
	(130, 130, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Adanya uraian Tugas masing-masing unit', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', 'Area 2,5', 'Sedang', 4),
	(131, 131, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Implementasi SOP', '1. SOP telah dibuat sesuai dengan\n    Peraturan Sekretaris Mahkamah Agung\n    R.I Nomor 002 Tahun 2012 tentang\n    Pedoman Penyusunan SOP di\n    Lingkungan MA dan Badan Peradilan\n    yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', 'Area 2,5', 'Berat', 4),
	(132, 132, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pelaksanaan absensi sesuai dengan Perma No. 7 Tahun 2016 dan SK KMA 071/KMA/SK/V/2008 (uji petik tiga bulan terakhir)', '1. Absensi manual dan finger print sesuai \n2. pengisian absensi manual sudah sesuai\n    ketentuan\n3. sudah diparaf dan digaris merah oleh petugas\n4. sudah dimonitoring dan dievaluasi', 'Area 2,3,5', 'Sedang', 4),
	(133, 133, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Izin keluar kantor menggunakan formulir sesuai Perma No. 7 Tahun 2016 dan SK KMA 071/KMA/SK/V/2008 atau surat tugas sesuai ketentuan (uji petik tiga bulan terakhir)', '1. Sudah selalu dilaksanakan\n2. Formulir ijin keluar kantor sesuai SK KMA\n3. Surat ijin keluar diketahui pimpinan\n4. Pengarsipan surat ijin keluar tertata dengan\n    rapi', 'Area 2,3,5', 'Sedang', 4),
	(134, 134, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Peta kekuatan pegawai, rencana kebutuhan pegawai, dan Daftar Urut Kepangkatan', '1. Sudah ada dan sudah tepat\n2. sudah ada dokumen Peta kekuatan pegawai\n3. terencananya kebutuhan pegawai\n4. Daftar urut kepangkatan diperbaharui\n', 'Area 3', 'Sedang', 4),
	(135, 135, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Baperjakat dan penempatan pegawai sudah sesuai dengan kompetensi ', '1. Sudah ada SK tim Baperjakat\n2. Sudah dilaksanakan \n3. Proses pelaksanaan baperjakat sesuai dengan\n    aturan yang berlaku (minimal 6 bulan sekali)\n4. Penempatan pegawai sudah sesuai\n    kompetensi', 'Area 2,3', 'Sedang', 4),
	(136, 136, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Analisa pengembangan kompetensi \n', '1. Sudah melakukan Analisa Pengembangan Kompetensi (Training Need Analysis)\n2. Rencana pengembangan kompetensi pegawai,\n    apakah mempertimbangkan hasil pengelolaan\n    kinerja pegawai\n3. Sudah tersedia data persentase kesenjangan \n    kompetensi pegawai yang ada dengan standar \n   kompetensi yang ditetapkan untuk masing-masing \n   jabatan\n4. Pegawai di Unit Kerja telah memperoleh\n    kesempatan/hak untuk mengikuti diklat\n    maupun pengembangan kompetensi lainnya\n5. unit kerja melakukan upaya pengembangan\n    kompetensi kepada pegawai (dapat melalui\n    pengikutsertaan pada lembaga pelatihan, in\n    house training, atau melalui coaching, atau\n    mentoring, dll)\n6. monitoring dan evaluasi terhadap hasil\n    pengembangan kompetensi dalam kaitannya\n    dengan perbaikan kinerja', 'Area 3', 'Berat', 6),
	(137, 137, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Arsip kepegawaian', '1. Tersusun secara sistematis sesuai jabatan,\n     lengkap dan rapi\n2. Data kepegawaian diperbarui\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', 'Area 2,3,5', 'Sedang', 4),
	(138, 138, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pengelolaan SIKEP', '1. Data Lengkap (100%)\n2. Data akurat\n3. Data terbarui\n4. Seluruh E doc SK Kepegawaian seluruh\n    pegawai teknis/ non teknis sudah di upload\n    (100%)\n5. Data untuk tanda tangan elektronik lengkap\n    (No HP, NIK, Email domain MA, uploud e_doc\n   KTP dengan format jpg atau jpeg dan berwarna)', 'Area 3', 'Berat', 5),
	(139, 139, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'RKP, RKGB dan usul pensiun', '1. RKP seluruhnya sudah dibuat \n     (untuk periode 1 tahun)\n2. RKGB seluruhnya sudah dibuat \n     (untuk periode 1 tahun) \n3. Usul pensiun sudah dibuat dan dikirim ke\n    Kanreg setempat                                      \n4. RKP, RKGB, dan usul pensiun sudah\n    terinformsikan (melalui papan atau monitor) ', 'Area 3', 'Berat', 4),
	(140, 140, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pencatatan surat masuk/keluar', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', 'Area 2', 'Ringan', 4),
	(141, 141, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pemberian sanksi dan penghargaan', '1. Sudah dilaksanakan sesuai hasil\n     evaluasi (data dukung SK Pimpinan)                                                              2. Ada Berita Acara\n3. Terdokumentasi dengan baik\n4. Terakomodir dalam sistem promosi dan\n    mutasi internal', 'Area 1,3,6', 'Berat', 4),
	(142, 142, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Sasaran Kerja Pegawai (SKP) dan penilaian prestasi kerja', '1. sasaran kerja pegawai telah dibuat          \n2. pengisian SKP sudah sesuai dengan Tusi\n3. penilaian prestasi kerja dilakukan per bulan\n4. sudah diarsipkan dan tertata', 'Area 2,3,5', 'Berat', 4),
	(143, 143, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Prosedur izin (keluar negeri,belajar,tugas belajar dan cuti)', '1. Sudah dilaksanakan sesuai dengan PP\n    Nomor 11 Tahun 2017, SK KMA 125\n    tahun 2009, perma 7 tahun 2016.\n2. Sudah terdokumentasi dengan baik', 'Area 3', 'Sedang', 2),
	(144, 144, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Penyusunan Keputusan Pimpinan sesuai dengan Peraturan Kepala Arsip Nasional Indonesia No. 2 Tahun 2014 ', '1. Sudah  sesuai \n2. sudah terdokumentasi \n3. sudah dimonitoring\n4. Sudah dievaluasi', 'Area 2', 'Ringan', 4),
	(145, 145, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Dokumentasi Rapat/ Notulen Rapat', '1. Ditunjuk penanggung jawab notulen oleh\n    Pimpinan satker yang ditetapkan dengan SK                                                2. Setiap rapat sudah dibuatkan notulen \n3. Setiap notulen didokumentasikan menjadi\n    satu kesatuan dengan undangan, foto dan\n    daftar hadir.\n4. Sudah terdokumentasi dengan baik', 'Area 2', 'Sedang', 4),
	(146, 146, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pengelolaan tenaga honorer\n', '1. Proses Perekrutan dilaksanakan secara\n    terbuka \n2. Ada kriteria kelulusan yang ditetapkan oleh\n    KPA  dan dituangkan dalam BA                                                  3. SK terdokumentasi dengan baik\n4. Evaluasi minimal 1 kali dalam setahun\n5. Pembiayaan oleh DIPA\n6. Ada kontrak kerja yang ditanda tangani KPA                                               ', 'Area 2,3', 'Sedang', 6),
	(147, 147, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pengisian Laporan Lembar kerja (LLK) dan penilaian Kinerja Pegawai (PKP)', '1. Sudah diisi secara rutin dan menggunakan\n    aplikasi\n2. Sudah diverifikasi oleh atasan langsung\n3. Menjadi salah satu bahan evaluasi kinerja ASN Pengadilan\n4. Terdokumentasi dengan baik', 'Area 3', 'Sedang', 4),
	(148, 148, 'UMUM DAN KEUANGAN', 'Pencatatan surat masuk/keluar', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', 'Area 2', 'Ringan', 4),
	(149, 149, 'UMUM DAN KEUANGAN', 'Adanya uraian Tugas masing-masing unit', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', 'Area 2,5', 'Sedang', 4),
	(150, 150, 'UMUM DAN KEUANGAN', 'Implementasi SOP', '1. SOP telah dibuat sesuai dengan\n     Peraturan Sekretaris Mahkamah Agung\n     R.I Nomor 002 Tahun 2012 tentang\n     Pedoman Penyusunan SOP di\n     Lingkungan MA dan Badan Peradilan\n     yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', 'Area 2,5', 'Berat', 4),
	(151, 151, 'UMUM DAN KEUANGAN', 'SK Pengelola BMN dan Laporan inventaris barang milik negara (SIMAK BMN) ', '1. Sudah ada SK\n2. Sudah dilaksanakan\n3. Sudah dilaporkan\n4. Diupdate \n5. tersedia data dukung', 'Area 4,5', 'Berat', 5),
	(152, 152, 'UMUM DAN KEUANGAN', 'Nilai Kapitalisasi Barang Milik Negara (BMN)', '1. Belanja barang peralatan dan mesin\n     diatas Rp.1.000.000,- dengan masa\n     manfaat lebih dari 1 tahun telah\n     menggunakan Akun Belanja Modal.\n2. Belanja barang gedung dan bangunan\n    diatas Rp.25.000.000,- dengan masa\n    manfaat lebih dari 1 tahun telah\n    menggunakan Akun Belanja Modal.\n3. Barang hasil pengadaan telah diinput\n    ke dalam daftar BMN pada aplikasi\n   SIMAK - BMN. ', 'Area 4,5', 'Berat', 3),
	(153, 153, 'UMUM DAN KEUANGAN', 'Pencatatan Aset  lainnya', '1. Sudah ada SK Tim Penilai Kondisi BMN\n     yang diperbaharui setiap tahun\n2. Laporan dari Tim Penilai kepada KPB\n    setahun sekali\n3. KPB membuat SK Penghentian pemakaian\n4. Register Transaksi Harian (RTH)\n    Penghentian Penggunaan BMN\n5. Usulan Penghapusan BMN', 'Area 4', 'Sedang', 5),
	(154, 154, 'UMUM DAN KEUANGAN', 'Laporan Pengawasan dan Pengendalian (WASDAL) BMN', ' 1. Sudah mengisi aplikasi Sistem Informasi\n     Manajemen Aset Negara (SIMAN)\n 2. Laporan Wasdal BMN sudah ditandatangani\n     oleh KPB setiap tahun\n 3. Laporan sudah dikirim ke KPKNL setempat\n     (sudah ada tanda terima)\n4. Terdokumentasi dengan baik', 'Area 2,5', 'Sedang', 4),
	(155, 155, 'UMUM DAN KEUANGAN', 'Penginputan Aset Tetap', '1. Kesesuaian jumlah dan harga barang yang\n    diinput pada SIMAK BMN saat pembelian\n2. Kesesuaian Spesifikasi Barang yang diinput\n3. Pengarsipan Dokumen Pembelian aset tetap\n    sudah tersusun dengan rapi \n4. Sudah di monitoring dan evaluasi', 'Area 2,4,5', 'Sedang', 4),
	(156, 156, 'UMUM DAN KEUANGAN', 'Penatausahaan Barang Persediaan', '1. Kesesuaian jumlah dan harga barang yang\n     diinput pada aplikasi persediaan saat\n     pembelian\n2. Dokumen permintaan barang persediaan\n    dari masing - masing bagian terdokumentasi\n    dengan baik\n3. Dokumen serah terima barang sudah di\n    tandatangani oleh masing - masing pihak\n4. Terdapat kartu pengawasan pengendalian\n     per item barang persediaan\n5. Laporan berita acara opname fisik barang\n    persediaan telah dilakukan per semester', 'Area 2,4,5', 'Sedang', 5),
	(157, 157, 'UMUM DAN KEUANGAN', 'Barang Persediaan Dipa 01 dan Dipa 03', '1. Data dan Barang Persediaan sesuai \n2. Barang tertata rapi \n3. Penyimpanan terpisah antara Dipa 01\n    dan Dipa 03\n4. Laporan diserahkan ke Sekretaris \n5. Kartu Kendali Pengawasan Barang Persediaan / ATK       ', 'Area 2,4,5', 'Sedang', 5),
	(158, 158, 'UMUM DAN KEUANGAN', 'Pengelolaan Kendaraan Dinas', '1. Penunjukan kendaraan dinas sudah\n    sesuai PMK 76/PMK.06/2015\n2. Penggunaan anggaran kendaraan dinas\n    tidak melebihi standar biaya masukan\n3. Kartu kendali penggunaan kendaraan\n    dinas telah dibuat\n4. Pembayaran pajak STNK telah dibayar\n    dengan tertib', 'Area 2,4,5', 'Sedang', 4),
	(159, 159, 'UMUM DAN KEUANGAN', 'Pengelolaan Rumah Dinas', '1. Perhitungan sewa rumah dinas telah\n     sesuai dengan keputusan menteri\n     KIMPRASWIL Nomor 373/UPTS/M/2001\n2. Pembayaran PBB rumah dinas telah\n    dibayar dengan tertib \n3. Terdokumentasi dengan baik\n4. Terdapat monitoring dan evaluasi.\n     terhadap Hakim yang mendapat fasilitas\n     rumah dinas dan tunjangan sewa rumah\n     dinas. \n5. Nilai HSBGN (Harga Satuan Bangunan\n    Gedung Negara) per wilayah telah diupdate\n    secara periodik dalam menghitung tarif\n    sewa.', 'Area 2,4,5', 'Sedang', 5),
	(160, 160, 'UMUM DAN KEUANGAN', 'SK Penunjukan Penghunian Rumah Dinas', '1. SK ditanda tangani KPB\n2.Tidak ada pemegang ganda Rumah dinas                                                             3. Membayar sewa sesuai peraturan\n    Permen PU No.22/PRT/M/2008\n4. PBB dibayar oleh penghuni\n5.Terdokumentasi dengan baik', 'Area 4,5', 'Sedang', 5),
	(161, 161, 'UMUM DAN KEUANGAN', 'SK Kendaraan Dinas', '1. SK ditanda tangani KPB\n2. Tidak ada pemegang ganda Kendaraan\n    dinas   \n3. Bukti Biaya Pemeliharaan dan\n    Operasional\n4.Terdokumentasi dengan baik', 'Area 4,5', 'Sedang', 4),
	(162, 162, 'UMUM DAN KEUANGAN', 'SK Perangkat IT', '1. SK ditanda tangani KPB\n2. Tidak ada pemegang ganda Perangkat IT                                                             3. Bukti Biaya Pemeliharaan                                             \n4. Terdokumentasi dengan baik', 'Area 4,5', 'Sedang', 4),
	(163, 163, 'UMUM DAN KEUANGAN', 'Pemeliharaan sarana dan prasarana (perangkat IT, rumah dinas, kendaraan dinas, perlengkapan persidangan, kalung hakim dll)', '1. Terpelihara dengan baik\n2. Dirawat secara rutin\n3. Adakartu kontrol\n4. SK BMN sesuai peruntukan', 'Area 4,5', 'Sedang', 4),
	(164, 164, 'UMUM DAN KEUANGAN', 'Perawatan dan Pengelolaan Server', '1. Dirawat secara rutin dan Terpelihara dengan baik \n2. Tersedia Rak Server pada ruang tersendiri\n3. Ada kartu kontrol dan kartu kontrol terisi dengan baik\n4. Tersedia 2 (dua) unit AC yang dinyalakan bergantian', 'Area 2,6', 'Sedang', 4),
	(165, 165, 'UMUM DAN KEUANGAN', 'Genset', '1. Sudah dilengkapi Genset dan masuk dalam BMN\n2. Kapasitas tersedia sesuai kebutuhan\n3. Dirawat secara rutin dan Terpelihara dengan baik \n4. BBM sudah dianggarkan', 'Area 4,6', 'Sedang', 4),
	(166, 166, 'UMUM DAN KEUANGAN', 'Daftar barang ruangan & Labelisasi barang milik negara', '1. DBR sudah diperbaharui setiap tahun\n2. Sudah dilaporkan pada pimpinan\n3. Seluruh barang BMN sudah Labelisasi \n4. DBR ditandatangani oleh KPB dan\n    Penaggung Jawab ruangan\n5. Nomor inventaris BMN pada Label\n    sesuai dengan SIMAK BMN', 'Area 2,4,5', 'Sedang', 5),
	(167, 167, 'UMUM DAN KEUANGAN', 'Layout jalur keluar masuk kendaraan & Pengaturan lahan parkir', '1. Jalur keluar masuk kendaraan sudah\n   diatur                                                \n2. Tertata dengan baik\n3. Ada petugas parkir \n4. Sudah dipisahkan antara karyawan\n    dengan pengunjung', 'Area 6', 'Ringan', 4),
	(168, 168, 'UMUM DAN KEUANGAN', 'Jalur masuk gedung pengadilan', '1. Sudah satu pintu\n2. Diawasi oleh CCTV\n3. Dijaga oleh Petugas Keamanan \n4. Diberikan kartu tamu/pengunjung', 'Area 6', 'Ringan', 4),
	(169, 169, 'UMUM DAN KEUANGAN', 'Jalur evakuasi dan titik kumpul', 'Sudah ada, tepat dan sudah disosialisasikan', 'Area 6', 'Ringan', 1),
	(170, 170, 'UMUM DAN KEUANGAN', 'Simulasi tanggap darurat dan kebakaran dengan instansi terkait', '1. Tim penanganan bencana sudah\n    dibentuk\n2. Simulasi sudah dilaksanakan\n3. Diulang setiap tahun\n4. Sudah dimonitoring dan dievaluasi \n   (dibuktikan dengan data dukung) ', 'Area 5,6', 'Ringan', 4),
	(171, 171, 'UMUM DAN KEUANGAN', 'Sarana alat pemadam api ringan (APAR)', '1. Tersedia APAR\n2. Penempatan sudah sesuai\n3. APAR tidak kadaluarsa\n4. Terkontrol dengan rutin', 'Area 5,6', 'Sedang', 4),
	(172, 172, 'UMUM DAN KEUANGAN', 'CCTV', '1. Tersedia CCTV dengan jumlah yang\n     sesuai\n2. Monitor diruangan KPT\n3. Penempatan sesuai\n4. Perawatan secara rutin (data dukung\n    kartu perawatan)\n5. Kondisi layak/ Tidak ada yang rusak', 'Area 5', 'Ringan', 5),
	(173, 173, 'UMUM DAN KEUANGAN', 'Petugas keamanan', '1. Bersertifikasi\n2. Menggunakan Seragam\n3. Menggunakan peralatan keamanan\n4. Memahami prosedur pengamanan dan\n    evakuasi\n5. 3S (Senyum,Salam,Sapa)', 'Area 2,3,6\n', 'Ringan', 5),
	(174, 174, 'UMUM DAN KEUANGAN', 'Sarana monitoring realisasi anggaran DIPA 01 dan DIPA 03', '1. Tersedia sarana publikasi/monitoring\n     realisasi\n2. Terpublikasikan pada Papan Pengumuman\n3. Terpublikasi di Website\n4. Diperbaharui per bulan', 'Area 2,5,6', 'Sedang', 4),
	(175, 175, 'UMUM DAN KEUANGAN', 'Tersedia informasi tentang : \n1. Visi dan Misi,\n2. Papan daftar nama hakim, \n3. Papan daftar nama mediator, \n4. Alur perkara, \n5. Alur pengajuan dan penanganan layanan\n    bantuan hukum, \n6. Gugatan sederhana, \n7. Informasi panjar biaya perkara, ', 'Tersedia seluruhnya\n', 'Area 2,6\n', 'Ringan', 1),
	(176, 176, 'UMUM DAN KEUANGAN', 'Sarana pendukung : \n1. Ruang Posbakum, \n2. Ruang jaksa, \n3. Ruang penasihat hukum, \n4. Ruang Laktasi, \n5. Ruang tunggu pengunjung, \n6. Ruang  kesehatan,\n7. Perpustakaan ', 'Lengkap dan layak\n', 'Area 6\n', 'Sedang', 1),
	(177, 177, 'UMUM DAN KEUANGAN', 'Kontrak kantin (PNBP Kantin)', '1. Sudah ada perjanjian sewa\n2. Bukti setoran ke Negara\n3. Perhitungan sewa sudah dilakukan oleh\n    KPKNL\n4. SK Penetapan Pelaksanaan sewa BMN dari \n    Sekretaris MA\n5. Terdokumentasi', 'Area 4,5', 'Ringan', 5),
	(178, 178, 'UMUM DAN KEUANGAN', 'Perjalanan Dinas', '1. Pembebanan biaya perjalanan dinas\n     sudah sesuai dengan akun yang\n     tersedia\n2. Perjalanan dinas tersebut\n    menghasilkan output kinerja yang jelas\n3. Waktu dan tempat tujuan sudah sesuai\n    dengan surat tugas\n4. Terdokumentasi dengan baik.', 'Area 2,4,5', 'Sedang', 4),
	(179, 179, 'UMUM DAN KEUANGAN', 'Buku-buku keuangan\n1. Buku kas umum (dilengkapi dengan\n    LPJ/akhir bulan)\n2. Buku bank\n3. Buku bantu (Pengawasan kredit, uang\n    persediaan, SPM dan penyetoran pajak\n    PPH Pasal 21, 22 dan 23)', '1. Lengkap\n2. Akurat\n3. Bukti sesuai\n4. Sisa uang sama dengan brankas', 'Area 2,4,5', 'Berat', 4),
	(180, 180, 'UMUM DAN KEUANGAN', 'SK manajemen pengelolaan keuangan : \n1. SK KPA \n2. SK Pejabat Pembuat Komitmen\n3. SK bendahara pengeluaran/ bendahara\n     pemegang uang muka \n4.  Bendahara penerima, \n5. SK Pembantu Pengelola Keuangan', 'Lengkap\n', 'Area 4', 'Berat', 1),
	(181, 181, 'UMUM DAN KEUANGAN', 'Dokumen pertanggung jawaban telah disimpan dan diarsipkan', '1. Lengkap\n2. Tersusun rapi \n3. Tepat waktu\n4. Tersimpan dengan baik', 'Area 2,4,5', 'Berat', 4),
	(182, 182, 'UMUM DAN KEUANGAN', 'Prosedur Pendistribusian Barang (Berita Acara Serah Terima Barang dan Tanda Terima Barang)', '1. Terdata dengan baik\n2. Jumlah sesuai\n3. Tersedia Berita Acara Serah Terima Barang\n4. Tersedia tanda terima', 'Area 2,4,5', 'Sedang', 4),
	(183, 183, 'UMUM DAN KEUANGAN', 'Monitoring uang persediaan di brankas bendahara oleh KPA setiap bulan', '1. Monitoring sudah dilaksanakan \n2. Berita Acara\n3. Dilaksanakan setiap bulan\n4. Sisa uang di brankas sesuai dengan\n    buku keuangan', 'Area 2,4,5', 'Berat', 4),
	(184, 184, 'UMUM DAN KEUANGAN', 'Satker sudah menginput aplikasi monev PP 39 Tahun 2006 dari Bapenas setiap triwulan ', '1. Sudah dilaksanakan\n2. Sudah dilaporkan pada pimpinan\n3. Diupdate setiap triwulan\n4. Sudah dilakukan monitoring dan\n    evaluasi', 'Area 2,4,5', 'Berat', 4),
	(185, 185, 'UMUM DAN KEUANGAN', 'Satker telah melakukan Rekon internal antara aplikasi SIMAK, BMN, SAIBA dan KOMDANAS setiap bulannya dengan membuat berita acara Rekon internal (mengetahui : operator SAIBA, operator, SIMAK, BMN dan KPA)', '1. Sudah dilaksanakan\n2. Sudah dilaporkan pada pimpinan\n3. Diupdate setiap bulan\n4. Tersedia data dukung', 'Area 2,4,5', 'Berat', 4),
	(186, 186, 'UMUM DAN KEUANGAN', 'Sistem Informasi Rencana Umum Pengadaan (SIRUP)', '1. KPA telah mengisi dan mengumumkan\n    seluruh paket pengadaan pada aplikasi\n    sirup di awal tahun anggaran', 'Area 2,4,5', 'Sedang', 1),
	(187, 187, 'PERENCANAAN, TI DAN PELAPORAN', 'Pencatatan surat masuk/keluar', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', 'Area 2', 'Ringan', 4),
	(188, 188, 'PERENCANAAN, TI DAN PELAPORAN', 'Adanya uraian Tugas masing-masing unit', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', 'Area 2,5', 'Sedang', 4),
	(189, 189, 'PERENCANAAN, TI DAN PELAPORAN', 'Implementasi SOP', '1. SOP telah dibuat sesuai dengan\n   Peraturan Sekretaris Mahkamah Agung\n   R.I Nomor 002 Tahun 2012 tentang\n   Pedoman Penyusunan SOP di\n   Lingkungan MA dan Badan Peradilan\n   yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', 'Area 2,5', 'Berat', 4),
	(190, 190, 'PERENCANAAN, TI DAN PELAPORAN', 'Satker sudah mengisi aplikasi monev smart setiap bulannya dan melaporkan kepada pimpinan.', '1. Indikator kinerja telah mengikuti kaidah\n    SMART\n2. Pengisian data sudah dilakukan\n    secara tertib setiap bulan\n3. Sekretaris melakukan monitoring perbulan\n4. Sudah dievaluasi', 'Area 2,4,5', 'Sedang', 4),
	(191, 191, 'PERENCANAAN, TI DAN PELAPORAN', 'Penyusunan RKAKL', '1. Telah melihatkan pimpinan dan unit lain dalam penyusunan RKAKL\n2. ada instrumen TOR dan RAB \n3. Di input melalui aplikasi SAKTI\n4. sudah dilaksanakan monev', 'Area 2,4,5', 'Berat', 4),
	(192, 192, 'PERENCANAAN, TI DAN PELAPORAN', 'Pelaporan Keuangan satker DIPA 01 dan 03  (berdasarkan PMK no.22/PMK.05/2016) sesuai dengan standard akutansi pemerintah yang berlaku. ', '1. Adanya Neraca, \n2. Laporan Realisasi Anggaran (LRA), \n3. Laporan Oprasional (LO), \n4. Laporan Perubahan Equitas (LPE) dan \n5. catatan atas laporan keuangan (calk)', 'Area 2,4,5', 'Berat', 5),
	(193, 193, 'PERENCANAAN, TI DAN PELAPORAN', 'Layanan Hukum bagi masyarakat kurang mampu berdasarkan PERMA No 1 Tahun 2014', '1. Sudah melakukan inovasi untuk mengoptimalkan pelaksanaan layanan hukum pembebasan biaya perkara (prodeo) pada masyarakat kurang mampu berdasarkan PERMA No 1 Tahun 2014\n2. Sudah melakukan Sosialisasi sesuai SE Dirjen Badilum Nomor 3 Tahun 2020 dan Nomor 1 Tahun 2022 baik secara Internal maupun Eksternal \n3. Pelaporan secara tertib menggunakan aplikasi dari Badilum\n4. Sudah dilaksanakan monev', 'Area 5,6', 'Berat', 4),
	(194, 194, 'PERENCANAAN, TI DAN PELAPORAN', 'Kepatuhan Backup data sesuai Instruksi Dirjen Badilum Nomor 3102/DJU/SK/HM02.3/9/2019', '1. Melakukan backup data minimal\n    1x dalam satu hari\n2. Melakukan singkronisasi ke PT\n    minimal 1x dalam satu hari\n3. Melakukan singkronisasi ke MA\n    minimal 1x dalam satu hari\n4. Melakukan monitoring dan evaluasi\n    terhadap backup data ', 'Area 2,5,6', 'Berat', 4),
	(195, 195, 'PERENCANAAN, TI DAN PELAPORAN', 'Standarisasi website pengadilan \n(SK Dirjen Badilum No.1364/DJU/SK/HM.02.3/5/2021 tentang Standarisasi Website Pengadilan Di Lingkungan Peradilan Umum)', '1. Tampilan website menggunakan template latar\n     belakang merah sesuai ketentuan\n2. Alamat Website menggunakan domain resmi\n    pemerintahan\n3. Web dapat diakses kaum disabilitas\n4. Data selalu terupdate (termasuk profil\n    pengadilan dan berita)\n5. Keterbukaan informasi :\n    - Profil (struktur organisasi,LHKPN,dll)\n    - Pelayanan dasar/standar pelayanan\n      (prosedur beracara,biaya penyelesaian\n      perkara, agenda sidang)\n    - Hak masyarakat (hak bantuan hukum dan\n      biaya perkara cuma-cuma,dll)\n    - Prosedur pengaduan\n    - Ringkasan LKjIP\n    - LRA dan RKAKL\n6. Publikasi IKM, format sesuai dengan\n    Lampiran IV Permenpan  RB No 14 tahun\n    2017 \n7. Publikasi IPAK, format sesuai dengan\n    Lampiran IV Permenpan  RB No 14 tahun\n    2017', 'Area 2,6\n', 'Berat', 7);
/*!40000 ALTER TABLE `apm` ENABLE KEYS */;

-- membuang struktur untuk table amora.assesment_eksternal
CREATE TABLE IF NOT EXISTS `assesment_eksternal` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `semester` varchar(50) DEFAULT NULL,
  `tahun` varchar(50) DEFAULT NULL,
  `file_id` text,
  `link` text,
  `nama_file` text,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

-- Membuang data untuk tabel amora.assesment_eksternal: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `assesment_eksternal` DISABLE KEYS */;
/*!40000 ALTER TABLE `assesment_eksternal` ENABLE KEYS */;

-- membuang struktur untuk table amora.assesment_internal
CREATE TABLE IF NOT EXISTS `assesment_internal` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `semester` varchar(50) DEFAULT NULL,
  `tahun` varchar(50) DEFAULT NULL,
  `file_id` text,
  `link` text,
  `nama_file` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.assesment_internal: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `assesment_internal` DISABLE KEYS */;
/*!40000 ALTER TABLE `assesment_internal` ENABLE KEYS */;

-- membuang struktur untuk table amora.bagian
CREATE TABLE IF NOT EXISTS `bagian` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nama_bagian` varchar(50) DEFAULT NULL,
  `level` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.bagian: ~11 rows (lebih kurang)
/*!40000 ALTER TABLE `bagian` DISABLE KEYS */;
INSERT INTO `bagian` (`id`, `nama_bagian`, `level`) VALUES
	(3, 'KEPANITERAAN PERDATA', 'perdata'),
	(4, 'KEPANITERAAN HUKUM', 'hukum'),
	(5, 'KEPANITERAAN PIDANA', 'pidana'),
	(6, 'SUBBAG ORTALA', 'ortala'),
	(7, 'SUBBAG UMUM DAN KEUANGAN', 'umum'),
	(8, 'SUBBAG PTIP', 'ptip'),
	(9, 'PANITERA', 'panitera'),
	(10, 'SEKRETARIS', 'sekretaris'),
	(11, 'KETUA', 'ketua'),
	(12, 'WAKIL KETUA', 'wakil'),
	(13, 'ADMINISTRATOR', 'administrator');
/*!40000 ALTER TABLE `bagian` ENABLE KEYS */;

-- membuang struktur untuk table amora.google_client
CREATE TABLE IF NOT EXISTS `google_client` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `client_id` text,
  `client_secret` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.google_client: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `google_client` DISABLE KEYS */;
INSERT INTO `google_client` (`id`, `client_id`, `client_secret`) VALUES
	(1, '226119502573-m72er8rcdk1uhga8sk8msea3u749bndv.apps.googleusercontent.com', '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');
/*!40000 ALTER TABLE `google_client` ENABLE KEYS */;

-- membuang struktur untuk table amora.link_apm
CREATE TABLE IF NOT EXISTS `link_apm` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `area` varchar(50) DEFAULT NULL,
  `nomor_apm` int(10) unsigned DEFAULT NULL,
  `nomor_sub_apm` int(10) unsigned DEFAULT NULL,
  `semester` varchar(50) DEFAULT NULL,
  `tahun` varchar(50) DEFAULT NULL,
  `id_dok` text,
  `link` text,
  `nama_file` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.link_apm: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `link_apm` DISABLE KEYS */;
INSERT INTO `link_apm` (`id`, `area`, `nomor_apm`, `nomor_sub_apm`, `semester`, `tahun`, `id_dok`, `link`, `nama_file`) VALUES
	(1, 'KETUA', 1, 1, 'I', '2022', '1u1yLlnp7v6V229bYSxch7ePD2H-TQ8h7', 'https://drive.google.com/file/d/1u1yLlnp7v6V229bYSxch7ePD2H-TQ8h7/view?usp=drivesdk', '1-1-I-2022.pdf'),
	(2, 'KETUA', 1, 10, 'II', '2022', '1r0qDm-1SNxPUkL_Ub04ZVwrKW2-1bVJy', 'https://drive.google.com/file/d/1r0qDm-1SNxPUkL_Ub04ZVwrKW2-1bVJy/view?usp=drivesdk', '1-10-II-2022.pdf'),
	(3, 'PANITERA PENGGANTI', 107, 1, 'I', '2022', '1X-CdRMLo7DXb0JB_N6VtiFd5qnFDPvNn', 'https://drive.google.com/file/d/1X-CdRMLo7DXb0JB_N6VtiFd5qnFDPvNn/view?usp=drivesdk', '107-1-I-2022.pdf');
/*!40000 ALTER TABLE `link_apm` ENABLE KEYS */;

-- membuang struktur untuk table amora.mis
CREATE TABLE IF NOT EXISTS `mis` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uraian` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.mis: ~27 rows (lebih kurang)
/*!40000 ALTER TABLE `mis` DISABLE KEYS */;
INSERT INTO `mis` (`id`, `uraian`) VALUES
	(1, 'Data delegasi belum dilaksanakan'),
	(2, 'Data penahanan yang habis dalam 15 hari'),
	(3, 'Data Putusan yang belum diminutasi'),
	(4, 'Data perkara pidana yang belum berisi tanggal BHT'),
	(5, 'Data perkara perdata yang belum berisi tanggal BHT'),
	(6, 'Data perkara banding yang belum berisi tanggal BHT'),
	(7, 'Data perkara kasasi yang belum berisi tanggal BHT'),
	(8, 'Data perkara yang data saksi tidak lengkap'),
	(9, 'Data perkara sudah putus yang belum diberitahukan'),
	(10, 'Data banding belum dikirim'),
	(11, 'Data kasasi belum dikirm'),
	(12, 'Data PK belum dikirim'),
	(13, 'Perkara Perdata belum berisi Edoc Petitum'),
	(14, 'Perkara Pidana belum berisi Edoc Dakwaan'),
	(15, 'Perkara Putusan Belum Anonimisasi'),
	(16, 'Jadwal mediasi hari ini'),
	(17, 'Perkara yang belum dilakukan penundaan'),
	(18, 'Panggilan belum dilaksanakan atau Relas belum diupload'),
	(19, 'Sisa panjar perkara tingkat pertama yang telah putus dan belum dikembalikan'),
	(20, 'Sisa panjar perkara tingkat banding yang telah putus dan belum dikembalikan'),
	(21, 'Sisa panjar perkara tingkat kasasi yang telah putus dan belum dikembalikan'),
	(22, 'Data perkara yang belum upload BA'),
	(23, 'Data perkara yang belum diserahkan ke bagian hukum'),
	(24, 'Data perkara yang belum belum terdapat data court calendar sampai putusan atau penetapan'),
	(25, 'Edoc court calendar belum upload'),
	(26, 'Ecourt belum didaftarkan'),
	(27, 'Publikasi tidak sesuai');
/*!40000 ALTER TABLE `mis` ENABLE KEYS */;

-- membuang struktur untuk table amora.parent_folder_akreditasi
CREATE TABLE IF NOT EXISTS `parent_folder_akreditasi` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `folder` varchar(50) DEFAULT NULL,
  `folder_id` text,
  `link_folder` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.parent_folder_akreditasi: ~2 rows (lebih kurang)
/*!40000 ALTER TABLE `parent_folder_akreditasi` DISABLE KEYS */;
INSERT INTO `parent_folder_akreditasi` (`id`, `folder`, `folder_id`, `link_folder`) VALUES
	(2, 'checklist', '1gKWnIHGdY8MJpSBNvC7fx3twrv3FQMt_', 'https://drive.google.com/drive/folders/1gKWnIHGdY8MJpSBNvC7fx3twrv3FQMt_?usp=share_link'),
	(3, 'ass_internal', '1I6c0Xi6s67dFgMpzeFuyHAJt_LCYMqRf', 'https://drive.google.com/drive/folders/1I6c0Xi6s67dFgMpzeFuyHAJt_LCYMqRf?usp=share_link'),
	(4, 'ass_eksternal', '1Z-p1gLP2xwQLloYZr-8o1pkmwqyTnWNV', 'https://drive.google.com/drive/folders/1Z-p1gLP2xwQLloYZr-8o1pkmwqyTnWNV?usp=share_link');
/*!40000 ALTER TABLE `parent_folder_akreditasi` ENABLE KEYS */;

-- membuang struktur untuk table amora.redirect_uri_akreditasi
CREATE TABLE IF NOT EXISTS `redirect_uri_akreditasi` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `method` varchar(50) DEFAULT NULL,
  `uri` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.redirect_uri_akreditasi: ~5 rows (lebih kurang)
/*!40000 ALTER TABLE `redirect_uri_akreditasi` DISABLE KEYS */;
INSERT INTO `redirect_uri_akreditasi` (`id`, `method`, `uri`) VALUES
	(3, 'upload ass internal', 'akreditasi/upload_internal_drive'),
	(4, 'hapus file internal', 'akreditasi/hapus_internal_drive'),
	(5, 'upload checklist', 'akreditasi/upload_to_drive'),
	(6, 'upload ass eksternal', 'akreditasi/upload_eksternal_drive'),
	(7, 'hapus file eksternal', 'akreditasi/hapus_eksternal_drive');
/*!40000 ALTER TABLE `redirect_uri_akreditasi` ENABLE KEYS */;

-- membuang struktur untuk table amora.sop
CREATE TABLE IF NOT EXISTS `sop` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nama_sop` varchar(500) DEFAULT NULL,
  `nomor_sop` varchar(500) DEFAULT NULL,
  `bagian` varchar(100) DEFAULT NULL,
  `file_sop` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.sop: ~2 rows (lebih kurang)
/*!40000 ALTER TABLE `sop` DISABLE KEYS */;
INSERT INTO `sop` (`id`, `nama_sop`, `nomor_sop`, `bagian`, `file_sop`) VALUES
	(1, 'SOP layana', '1/2022', '4', 'SOP_layana.pdf'),
	(2, 'SOP Posbakum', '2/2022', '4', NULL);
/*!40000 ALTER TABLE `sop` ENABLE KEYS */;

-- membuang struktur untuk table amora.surat_keputusan
CREATE TABLE IF NOT EXISTS `surat_keputusan` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nomor_sk` varchar(50) DEFAULT NULL,
  `perihal_sk` text,
  `penandatangan` varchar(50) DEFAULT NULL,
  `file_sk` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- Membuang data untuk tabel amora.surat_keputusan: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `surat_keputusan` DISABLE KEYS */;
INSERT INTO `surat_keputusan` (`id`, `nomor_sk`, `perihal_sk`, `penandatangan`, `file_sk`) VALUES
	(4, '1/eks/2022', 'fdsafasfdas', 'Ketua', '1_eks_2022.pdf');
/*!40000 ALTER TABLE `surat_keputusan` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
